Add GitHub Action to create issues for each TODO comment
build-trust/ockam pull request #2132
Opened 2021-10-30 15:28 UTC by frazar

## Current Behaviour

When a  `TODO`/`BUG`/`FIXME`/`HACK` comment is committed into the `develop` branch, nothing happens.

## Proposed Changes

When a  `TODO`/`BUG`/`FIXME`/`HACK` comment is committed into the `develop` branch, a new GitHub Issue is created to keep track of it.
Fixes  #1930.

Note that merging this PR would create >100 of new Issues, as seen in [my fork of the report](https://github.com/frazar/ockam/issues/) where I tested this Action.

Additionally, the labels of the new issues might be configured to something more appropriate.

## Checks

- [x] All commits in this Pull Request are [signed](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits).
- [x] All commits in this Pull Request follow the Ockam [commit message convention](https://www.ockam.io/learn/how-to-guides/contributing/CONTRIBUTING#commit-messages).
- [x] I accept the Ockam Community [Code of Conduct](https://www.ockam.io/learn/how-to-guides/high-performance-team/conduct/).
- [x] I have accepted the Ockam [Contributor Licence Agreement](https://www.ockam.io/learn/how-to-guides/contributing/cla/) by adding my Git/Github details in a row at the end of the [CONTRIBUTORS.csv](https://github.com/ockam-network/contributors/blob/master/CONTRIBUTORS.csv) file in a separate pull request to the [ockam-network/contributors](https://github.com/ockam-network/contributors) repository.

2021-10-30 19:49 UTC, metaclips requested changes
Thanks @frazar for this amazing PR 🎉. Some minor changes left then we merge 🚀

2021-10-30 19:49 UTC, metaclips commented on .github/workflows/track_todo.yml
> +      uses: ribtoks/tdg-github-action@master
Can we use a commit version of `ribtoks/tdg-github-action`  instead of master branch. Latest commit is `b389a3667310bc373cb771fe05dac180ce0351e6`

2021-10-30 19:49 UTC, metaclips commented on .github/workflows/track_todo.yml
> +    runs-on: ubuntu-latest
We should pin to `ubuntu-20.04` as other workflows

2021-10-30 19:49 UTC, metaclips commented on .github/workflows/track_todo.yml
> +      with:
Let's add a `Label` with name TODO so we can easily track these kind of issues cc @mrinalwadhwa

2021-10-30 19:49 UTC, metaclips commented on .github/workflows/track_todo.yml
> +    - uses: actions/checkout@master
Lets pin `actions/checkout` to a commit version, we use `actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f`.

2021-11-01 17:04 UTC, frazar commented
Thanks for your code review! Should be ready for a second round now.

2021-11-01 18:04 UTC, metaclips approved these changes
Way to go @frazar 🚀

2022-01-03 20:29 UTC, mrinalwadhwa commented
@frazar Thank you for taking time to contribute.

Sorry that we haven't merged this so far.
I fear that turning this on will crate too many new issues and hesitated on the merge ... maybe a better setup would be a single issue that tracks a checklist of TODOs. What do you think?

Thank you and happy new year.

2022-01-05 10:00 UTC, frazar commented
> Sorry that we haven't merged this so far.

No worries! I understand this PR has a significant impact on the project, so you should carefully weigh whether or not to merge.
I am not a project maintainer, so I don't really feel entitled to an opinion. But since you asked (thank you!), I am going to express my point of view.

Personally, I do not think that having many open Issues is a problem _per se_, but I agree that having many _non-triaged_ Issues is not ideal. Indeed, going through all these Issues and applying the correct labels would take precious maintainer time. 

However, I believe that many non-triaged Issues are better than no Issues at all. The triaging process is not required to happen right away, and the amount of non-triaged Issues is expected to decrease over time. It is also possible to introduce a "needs-triage" label so that the auto-generated Issues can be filtered out quickly.

> maybe a better setup would be a single issue that tracks a checklist of TODOs. What do you think?

I see two drawbacks to this approach:
1. The GitHub Action used in this PR does not support such functionality, so it would require implementing it. 
2. Having a single Issue page would actually make Issue triaging harder since maintainers would need to manually create the new Issues.

2022-05-16 04:53 UTC, mrinalwadhwa commented
Hey @frazar for the time being, we decided to not create so many issue based on TODOs. Thank you so much for working on this, I regret that we couldn't land it. I'm closing this PR for now. Thank you 🙏

2022-05-16 04:53 UTC, closed without merging