chore(docs): review messaging docs
build-trust/ockam pull request #2660
Opened 2022-04-15 07:28 UTC by adrianbenavides

2022-04-19 21:33 UTC, hairyhum reviewed
Line breaks in some places are intended to deliver logical statements. I'm not sure it would be right to just remove them. Maybe we can use some other way to highlight that?

2022-04-25 21:58 UTC, hairyhum requested changes

2022-04-25 21:58 UTC, hairyhum commented on documentation/architecture/messaging/Accessibility.md
> -Such forwarding worker is called **proxy worker**
Let's keep the separate lines here

2022-04-25 21:58 UTC, hairyhum commented on documentation/architecture/messaging/Reliability.md
> -Retries can be used to improve delivery reliability.
Let's use a list here 
```
- Given
- If
- Then
```

2022-04-25 21:58 UTC, hairyhum commented on documentation/architecture/messaging/Reliability.md
> -Given `DM(A->B) = {0.5, 1}`
Let's use a list here 
```
- Given
- If
- Then
```

2022-04-25 21:58 UTC, hairyhum commented on documentation/architecture/messaging/Reliability.md
>  If we have a pipeline of routes `A->X; X->B`, in which `R(A->X) -> 1` and `R(X->B) -> 1`
Let's use a list here 
```
- If
- and
- Then
```

2022-04-25 21:58 UTC, hairyhum commented on documentation/architecture/messaging/Sessions.md
> -If "create" message route is backtraced, reply route can be a backtrace to the original message.
Let's keep lines separate here

2022-05-04 06:51 UTC, adrianbenavides commented
Sorry for the delay @hairyhum, I just kept forgetting about this PR. I've applied all the changes you requested, so it should be ready now!

2022-05-04 22:39 UTC, hairyhum approved these changes

2022-05-09 18:33 UTC, hairyhum commented
@adrianbenavides please rebase and squash

2022-05-10 09:15 UTC, adrianbenavides commented
> @adrianbenavides please rebase and squash

ready!

2022-05-10 17:28 UTC, hairyhum approved these changes

2022-05-10 17:28 UTC, merged