verifier and authenticator
build-trust/ockam pull request #3253
Opened 2022-08-16 20:01 UTC by twittner

Continuation of #2965. Renames signer to verifier and changes the direct authenticator to work on enroller files. Also adds ways to start the services from command line.

2022-08-16 21:24 UTC, hairyhum commented
Is there a way to run those services in a node? We currently run the sidecar node as 
`ockam node create -v -f --api-address=127.0.0.1:4100 sidecar`
and the identity service is started with the node.

Is verifier service also started or we need some way to do that?

Also can we pass some arguments to start a node with CA services?

2022-08-16 21:43 UTC, mrinalwadhwa commented
@hairyhum the updated command should be:

```
ockam node create sidecar --foreground --tcp-listener-address 127.0.0.1:4100 -vvv
```

2022-08-16 22:02 UTC, SanjoDeundiak requested changes
My main concern is Arc that wraps Identity. Other things can be tackled later

2022-08-16 22:02 UTC, SanjoDeundiak commented on implementations/rust/ockam/ockam_core/src/vault/verifier.rs
> +
Let's add it to all traits (at list in this module)

2022-08-16 22:02 UTC, SanjoDeundiak commented on implementations/rust/ockam/ockam_api/src/verifier.rs
> +            Some(Method::Get) => match req.path_segments::<2>().as_slice() {
I guess it should be POST actions/verify

2022-08-16 22:02 UTC, SanjoDeundiak commented on implementations/rust/ockam/ockam_api/src/verifier.rs
> +                            attr.put(EXPIRES_AT, &buff.get_ref()[..buff.position()]);
How about having VerifyResponse, that would have attributes and expire fields?

2022-08-16 22:02 UTC, SanjoDeundiak commented on implementations/rust/ockam/ockam_api/src/verifier.rs
> +    ) -> Result<Either<ResponseBuilder<Error<'_>>, CredentialData<'a, Verified>>> {
Well, that looks ugly, but we haven't had pretty solution to that problem I guess

2022-08-16 22:02 UTC, SanjoDeundiak commented on implementations/rust/ockam/ockam_api/src/verifier.rs
> +        if now < data.expires_at() {
It's `>=`, isn't it?

2022-08-16 22:02 UTC, SanjoDeundiak commented on implementations/rust/ockam/ockam_api/src/verifier.rs
> +        if let Some(PROJECT_MEMBER_SCHEMA) = data.schema() {
I don't think we should check any attributes here, this verification can be generic to verify any credential. Caller should figure out what are the schema and needed keys&values for that credential to authorize certain action

2022-08-16 22:02 UTC, SanjoDeundiak commented on implementations/rust/ockam/ockam_api/src/authenticator/direct.rs
> +    ident: Arc<Identity<V>>,
What is the purpose of Arc here?

2022-08-16 22:02 UTC, SanjoDeundiak commented on implementations/rust/ockam/ockam_api/src/authenticator/direct.rs
> +                            .with_attribute(PROJECT_ID, &self.project)
Should be {"project_id": "123ef"}, {"role": "member"}

2022-08-16 22:02 UTC, SanjoDeundiak commented on implementations/rust/ockam/ockam_api/src/lib.rs
> +pub struct Cbor<'a>(pub &'a [u8]);
Isn't that present in ockam_core::api?

2022-08-16 22:02 UTC, SanjoDeundiak commented on implementations/rust/ockam/ockam_api/src/nodes/service.rs
> +    identity: Option<Arc<Identity<Vault>>>,
Why it should be Arc?

2022-08-17 08:49 UTC, twittner commented on implementations/rust/ockam/ockam_api/src/verifier.rs
> +        if now < data.expires_at() {
:facepalm:

2022-08-17 08:50 UTC, twittner commented on implementations/rust/ockam/ockam_api/src/verifier.rs
> +            Some(Method::Get) => match req.path_segments::<2>().as_slice() {
Why the "actions" prefix?

2022-08-17 09:37 UTC, twittner commented
> > Also adds ways to start the services from command line.
> 
> We currently run the sidecar node as `ockam node create -v -f --api-address=127.0.0.1:4100 sidecar` and the identity service is started with the node.
> 
> Are we supposed to do that differently now?

TBD. Currently the verifier and authenticator services are not started automatically so they require additional commands, e.g.

```
> ockam service start verifier --node foo
Verifier service started at address: verifier
> ockam service start authenticator --node foo --enrollers /tmp/enrollers.json --project project42
> Authenticator service started at address: authenticator
```

> Also can we have an API doc for those services with response codes data formats for request/response?

schema.cddl has been updated with verify request/response structures.

2022-08-17 11:59 UTC, SanjoDeundiak commented on implementations/rust/ockam/ockam_api/src/verifier.rs
> +            Some(Method::Get) => match req.path_segments::<2>().as_slice() {
Because POST verify means something like "add an object of type verify"

2022-08-17 12:19 UTC, SanjoDeundiak commented
@mergifyio rebase

2022-08-17 12:21 UTC, SanjoDeundiak approved these changes

2022-08-17 12:35 UTC, merged