chore(Rust): Implement changes outlined in #3560
build-trust/ockam pull request #3574
Opened 2022-10-04 14:36 UTC by AntoniosBarotsis

Closes #3560

Decouples [`set_default_node`](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/configuration/set_default_node.rs)'s implementation from the `run` method for easier error handling.

2022-10-04 15:41 UTC, mrinalwadhwa commented
@AntoniosBarotsis Thank you for spending time on this, before we can merge please

- [ ] Accept the Ockam [Contributor License Agreement](https://github.com/build-trust/ockam-contributors/blob/main/CLA.md) by adding your Git/Github details in a row at the end of the [CONTRIBUTORS.csv](https://github.com/build-trust/ockam-contributors/blob/main/CONTRIBUTORS.csv) file in a separate pull request to the [build-trust/ockam-contributors](https://github.com/build-trust/ockam-contributors) repository.

The easiest way to do this is to [edit the CONTRIBUTORS.csv](https://github.com/build-trust/ockam-contributors/edit/main/CONTRIBUTORS.csv) file in the github web UI and create a PR, this will make the commit as verified.

2022-10-04 16:16 UTC, AntoniosBarotsis commented
Just made [the PR](https://github.com/build-trust/ockam-contributors/pull/116) :)

2022-10-04 17:12 UTC, mrinalwadhwa commented
@AntoniosBarotsis I pushed some commit message updates to your branch to satisfy our commit message linter. It looks like Clippy is failing on the PR, could you please resolve those errors before we merge https://github.com/build-trust/ockam/actions/runs/3184031888/jobs/5191968966

2022-10-04 17:21 UTC, AntoniosBarotsis commented
It seems that I am not getting the error locally due to some compilation issues as I am on Windows, will fix but make sure to check it again just to be sure it's fine!

2022-10-04 17:50 UTC, mrinalwadhwa commented
@AntoniosBarotsis linters are happy now. The rust nightly checks can be ignored.
We can merge after @adrianbenavides has a change to review the change in his morning.

Thank you for an awesome first contribution 🥳

2022-10-05 06:22 UTC, adrianbenavides requested changes
Hey @AntoniosBarotsis, it looks pretty great. Just a small change and will be ready to merge!

2022-10-05 06:22 UTC, adrianbenavides commented on implementations/rust/ockam/ockam_command/src/configuration/set_default_node.rs
> +    }
You can simplify this if you don't map the errors manually:

```rust
options.config.get_node(name)?;
options
    .config
    .set_default_node(&get_final_element(name).to_owned());
options.config.persist_config_updates()?;
```

2022-10-05 15:55 UTC, adrianbenavides commented
@mergifyio rebase

2022-10-05 16:16 UTC, adrianbenavides approved these changes, later dismissed
Ready to merge @AntoniosBarotsis , thank you so much for your PR! :metal:

2022-10-06 06:37 UTC, adrianbenavides commented
@mergifyio rebase

2022-10-06 06:43 UTC, adrianbenavides approved these changes, later dismissed

2022-10-06 07:00 UTC, adrianbenavides approved these changes

2022-10-06 07:02 UTC, merged