Initial draft of changes
build-trust/ockam pull request #3635
Opened 2022-10-10 20:49 UTC by sanjayts

- [ ] All commits in this Pull Request are [signed](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) and Verified by Github.
- [ ] All commits in this Pull Request follow the Ockam [commit message convention](https://github.com/build-trust/.github/blob/main/CONTRIBUTING.md#commit-messages).
- [ ] I accept the Ockam Community [Code of Conduct](https://github.com/build-trust/.github/blob/main/CODE_OF_CONDUCT.md).
- [ ] I have accepted the Ockam [Contributor License Agreement](https://github.com/build-trust/ockam-contributors/blob/main/CLA.md) by adding my Git/Github details in a row at the end of the [CONTRIBUTORS.csv](https://github.com/build-trust/ockam-contributors/blob/main/CONTRIBUTORS.csv) file in a separate pull request to the [build-trust/ockam-contributors](https://github.com/build-trust/ockam-contributors) repository.

2022-10-11 06:58 UTC, adrianbenavides requested changes
I've left a small suggestion, but overall it's looking great @sanjayts. Thank you so much for looking into this :pray:

2022-10-11 06:58 UTC, adrianbenavides commented on implementations/rust/ockam/ockam_command/src/project/util.rs
> +                identity_id: None,
You should also pass the node_route and identity_id here based on the `Project`:

```rust
let node_route: Option<MultiAddr> = if project.access_route.is_empty() {
    Some(
        project
            .access_route
            .as_ref()
            .try_into()
            .context("Invalid project node route")?,
    )
} else {
    None
};

...

ProjectLookup {
    node_route,
    identity_id: project.identity_id.clone(),
    ...
}
```

2022-10-11 19:44 UTC, closed without merging

2022-10-11 20:38 UTC, sanjayts commented
@adrianbenavides Awesome, I have made the changes but due to merge conflicts had to create another PR. WDYT?

https://github.com/build-trust/ockam/pull/3636

2022-10-13 06:56 UTC, adrianbenavides commented
Sure, no problem, whatever works for you! I'll review it today :+1: