build(rust): Move cross config
build-trust/ockam pull request #3665
Opened 2022-10-15 11:43 UTC by duttaANI

## Current Behavior
Currently the configuration from cross lives in [Cross.toml](https://github.com/build-trust/ockam/blob/develop/Cross.toml)

## Proposed Changes
To move config in Cross.toml to Cargo.toml

Fixes : https://github.com/build-trust/ockam/issues/3626

## Checks

- [x] All commits in this Pull Request are [signed](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) and Verified by Github.
- [x] All commits in this Pull Request follow the Ockam [commit message convention](https://github.com/build-trust/.github/blob/main/CONTRIBUTING.md#commit-messages).
- [x] I accept the Ockam Community [Code of Conduct](https://github.com/build-trust/.github/blob/main/CODE_OF_CONDUCT.md).
- [x] I have accepted the Ockam [Contributor License Agreement](https://github.com/build-trust/ockam-contributors/blob/main/CLA.md) by adding my Git/Github details in a row at the end of the [CONTRIBUTORS.csv](https://github.com/build-trust/ockam-contributors/blob/main/CONTRIBUTORS.csv) file in a separate pull request to the [build-trust/ockam-contributors](https://github.com/build-trust/ockam-contributors) repository.

2022-10-15 15:10 UTC, metaclips requested changes
Thanks for an amazing pull request 🚀

2022-10-15 15:10 UTC, metaclips commented on Cargo.toml
> +[package.metadata.cross.target.aarch64-unknown-linux-musl]
Lets change `package.metadata.cross.target.aarch64-unknown-linux-musl` to `ockam_command.metadata.cross.target.aarch64-unknown-linux-musl`

2022-10-15 15:10 UTC, metaclips commented on Cargo.toml
> +dockerfile = "./tools/cross/Cross.Dockerfile.armv7"
`package.metadata.cross.target.armv7-unknown-linux-musleabihf` should be `ockam_command.metadata.cross.target.armv7-unknown-linux-musleabihf`

2022-10-20 16:26 UTC, metaclips-botter commented
❌ Orchestrator test on PR #3665 at commit `ed2c1acbeaf39092a313ffd31d64b45e56ca011e` failed

2022-10-22 16:10 UTC, mrinalwadhwa commented
@duttaANI thank you for removing the merge commit in #3714 
Closing this and merging #3714

2022-10-22 16:10 UTC, closed without merging