refactor(rust): refactored identity show command to use rpc abstraction
build-trust/ockam pull request #3668
Opened 2022-10-16 15:47 UTC by divyank-rs

## Current Behavior

The current implementation in identity show command is calling std::process::exit, which is something we want to stop using to handle errors properly and give the user a better-formatted output when a command fails.

## Proposed Changes

Relating to issue #3562 
1) Changed the implementation to use the node_rpc method as being used in [subscription](https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/subscription.rs#L52) command
2) Added implementations of `ockam_command::util::output` for `ShortIdentityResponse` and `LongIdentityResponse` to maintain current code quality and style
3) Marked 2 functions that were being used before as `allow(unused)` to prevent linting errors.

## Checks

- [x] All commits in this Pull Request are [signed](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) and Verified by Github.
- [x] All commits in this Pull Request follow the Ockam [commit message convention](https://github.com/build-trust/.github/blob/main/CONTRIBUTING.md#commit-messages).
- [x] I accept the Ockam Community [Code of Conduct](https://github.com/build-trust/.github/blob/main/CODE_OF_CONDUCT.md).
- [x] I have accepted the Ockam [Contributor License Agreement](https://github.com/build-trust/ockam-contributors/blob/main/CLA.md) by adding my Git/Github details in a row at the end of the [CONTRIBUTORS.csv](https://github.com/build-trust/ockam-contributors/blob/main/CONTRIBUTORS.csv) file in a separate pull request to the [build-trust/ockam-contributors](https://github.com/build-trust/ockam-contributors) repository.

2022-10-16 17:14 UTC, adrianbenavides requested changes
Looking great @divyank-rs! A couple of things to address:

1. You can delete the `unused` methods
2. Can you add the bats test you mentioned [here](https://github.com/build-trust/ockam/issues/3562#issuecomment-1279996444)?

2022-10-16 17:14 UTC, adrianbenavides commented on implementations/rust/ockam/ockam_command/src/util/api.rs
>  ) -> Result<(Response, models::identity::LongIdentityResponse<'_>)> {
You can also delete this method.

2022-10-16 17:14 UTC, adrianbenavides commented on implementations/rust/ockam/ockam_command/src/util/api.rs
>      Request::post("/node/identity/actions/show/long").encode(&mut buf)?;
You can go ahead and delete this method.

2022-10-17 13:28 UTC, adrianbenavides approved these changes, later dismissed
Awesome, thank you so much @divyank-rs for your contribution! :tada:

2022-10-17 15:10 UTC, mrinalwadhwa approved these changes

2022-10-17 15:11 UTC, mrinalwadhwa commented
@divyank-rs thank you for an awesome first contribution 🥳

2022-10-17 15:12 UTC, merged