refactor(rust): `tcp connection delete` use `rpc` abstraction
build-trust/ockam pull request #3792
Opened 2022-11-03 08:59 UTC by miles170

## Current Behavior

Currently the `tcp connection delete` command is using the `connect_to` abstraction.

## Proposed Changes

Closes #3594.

1. Replace `connect_to` by `node_rpc` abstraction.
2. Remove unused `connect_to` and `parse_response`
3. Add `delete a tcp connection` test

## Checks

- [x] All commits in this Pull Request are [signed](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) and Verified by Github.
- [x] All commits in this Pull Request follow the Ockam [commit message convention](https://github.com/build-trust/.github/blob/main/CONTRIBUTING.md#commit-messages).
- [x] I accept the Ockam Community [Code of Conduct](https://github.com/build-trust/.github/blob/main/CODE_OF_CONDUCT.md).
- [x] I have accepted the Ockam [Contributor License Agreement](https://github.com/build-trust/ockam-contributors/blob/main/CLA.md) by adding my Git/Github details in a row at the end of the [CONTRIBUTORS.csv](https://github.com/build-trust/ockam-contributors/blob/main/CONTRIBUTORS.csv) file in a separate pull request to the [build-trust/ockam-contributors](https://github.com/build-trust/ockam-contributors) repository.

2022-11-03 09:54 UTC, miles170 commented
May I ask for more issues that I can work on? Thanks😊

2022-11-04 09:20 UTC, adrianbenavides requested changes
Wow, we finally got rid of the `connect_to`! That's something to celebrate :laughing: 

I've left a couple of comments :+1:

2022-11-04 09:20 UTC, adrianbenavides commented on implementations/rust/ockam/ockam_command/src/tcp/connection/delete.rs
> +    rpc.request(request).await?;
You have to check the rpc was successful here:

```rust
rpc.is_ok()?;
```

2022-11-04 09:20 UTC, adrianbenavides commented on implementations/rust/ockam/ockam_command/src/tcp/connection/delete.rs
> +    println!("Tcp connection `{}` successfully delete", command.id);
We had a typo here, could you fix it while we are here please? `delete` -> `deleted`

2022-11-04 09:45 UTC, adrianbenavides commented
> May I ask for more issues that I can work on? Thanksblush

I will try to come up with more issues next week!

2022-11-09 09:53 UTC, adrianbenavides commented
Hey. @miles170, I'm closing this PR in favor of https://github.com/build-trust/ockam/pull/3828. @h20220145 had this issue assigned before this PR was submitted. Sorry I didn't realize sooner 🙏

2022-11-09 09:53 UTC, closed without merging