ci: add draft-binaries workflow
build-trust/ockam pull request #3830
Opened 2022-11-10 03:12 UTC by miles170

## Current Behavior

## Proposed Changes

Closes #3829.

Add a workflow that tests ockam release binaries from the specified git tag. 
Only the x86_64 binaries are tested since there is no native arm-based GitHub runner.

Check passed CI here: https://github.com/miles170/ockam/actions/runs/3433628809

## Checks

- [x] All commits in this Pull Request are [signed](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) and Verified by Github.
- [x] All commits in this Pull Request follow the Ockam [commit message convention](https://github.com/build-trust/.github/blob/main/CONTRIBUTING.md#commit-messages).
- [x] I accept the Ockam Community [Code of Conduct](https://github.com/build-trust/.github/blob/main/CODE_OF_CONDUCT.md).
- [x] I have accepted the Ockam [Contributor License Agreement](https://github.com/build-trust/ockam-contributors/blob/main/CLA.md) by adding my Git/Github details in a row at the end of the [CONTRIBUTORS.csv](https://github.com/build-trust/ockam-contributors/blob/main/CONTRIBUTORS.csv) file in a separate pull request to the [build-trust/ockam-contributors](https://github.com/build-trust/ockam-contributors) repository.

2022-11-10 12:07 UTC, metaclips requested changes
Thanks for an amazing PR @miles170. I left few suggestions for a merge

2022-11-10 12:07 UTC, metaclips commented on .github/workflows/draft-binaries.yml
> +        fileName: ockam.${{ matrix.target }}*
```bash
gh release download ${{ github.event.inputs.git_tag }} -p ockam.${{ matrix.target }}* -R build-trust/ockam
```
Should replace this action. More here https://cli.github.com/manual/gh_release_download

2022-11-10 12:07 UTC, metaclips commented on .github/workflows/draft-binaries.yml
> +        ./ockam.${{ matrix.target }} --version
This is a plus 🙂 and not really needed. We can `grep` to see if the version spewed out contains `${{ github.event.inputs.git_tag }}`

2022-11-10 15:47 UTC, miles170 commented
Check passed CI here: https://github.com/miles170/ockam/actions/runs/3438259508

2022-11-10 17:07 UTC, metaclips approved these changes
Thanks @miles170

2022-11-11 18:51 UTC, adrianbenavides approved these changes

2022-11-11 18:52 UTC, merged