refactor(rust): `identity show` stop retrieving from background node
build-trust/ockam pull request #3938
Opened 2022-12-16 14:31 UTC by miles170

## Current Behavior

Currently, the identity show command accepts a node_opts argument and retrieves identity from the background node.

## Proposed Changes

Closes #3937

1. replace argument `node_opts` with `name`
2. `identity show` now pulls identity from the cli state
3. remove the request handlers related to identities from the `NodeManager`

## Checks

- [x] All commits in this Pull Request are [signed](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) and Verified by Github.
- [x] All commits in this Pull Request follow the Ockam [commit message convention](https://github.com/build-trust/.github/blob/main/CONTRIBUTING.md#commit-messages).
- [x] I accept the Ockam Community [Code of Conduct](https://github.com/build-trust/.github/blob/main/CODE_OF_CONDUCT.md).
- [x] I have accepted the Ockam [Contributor License Agreement](https://github.com/build-trust/ockam-contributors/blob/main/CLA.md) by adding my Git/Github details in a row at the end of the [CONTRIBUTORS.csv](https://github.com/build-trust/ockam-contributors/blob/main/CONTRIBUTORS.csv) file in a separate pull request to the [build-trust/ockam-contributors](https://github.com/build-trust/ockam-contributors) repository.

2022-12-19 08:03 UTC, adrianbenavides requested changes
Looks pretty good! I left a small comment. Thanks for the PR 👍

2022-12-19 08:03 UTC, adrianbenavides commented on implementations/rust/ockam/ockam_command/src/util/mod.rs
> +pub fn print_rpc_response<T>(b: T, output_format: &OutputFormat) -> Result<T>
Since this is independent of the `Rpc` struct, I'd rename this to `print_command_response`.

2022-12-19 08:11 UTC, miles170 commented
Force-pushed with taking suggestion https://github.com/build-trust/ockam/pull/3938#discussion_r1051902924

2022-12-20 08:25 UTC, adrianbenavides approved these changes, later dismissed
Awesome, thanks for another great contribution @miles170, will get merged shortly! 🚀

2022-12-21 03:38 UTC, miles170 commented
Force-pushed with merge the latest changes from `develop`.

2022-12-22 07:52 UTC, adrianbenavides approved these changes

2022-12-22 08:02 UTC, merged