feat(rust): add command to enable confluent addon
build-trust/ockam pull request #4044
Opened 2023-01-10 09:36 UTC by adrianbenavides

2023-01-10 16:12 UTC, hairyhum commented
@adrianbenavides can you please provide an example on how to run the command?

2023-01-11 07:11 UTC, adrianbenavides commented
> @adrianbenavides can you please provide an example on how to run the command?

You can find how it is used in the bats test that I added on this PR. This command specifically looks like this:

```shell
ockam project addon enable confluent --project default --bootstrap-server host:0000 --api-key key --api-secret secret
```

2023-01-16 10:34 UTC, mszpakowski requested changes
Not fluent in rust, but looks good from what I can discern.
The only thing we have to change is to remove the `api_key` field from the response.

2023-01-16 10:34 UTC, mszpakowski commented on implementations/rust/ockam/ockam_api/src/cloud/addon.rs
> +    #[cbor(b(2))] pub api_key: CowStr<'a>,
After the discussion during the last demo I have removed the `api_key` from the response schema

2023-01-17 12:31 UTC, mszpakowski approved these changes, later dismissed
LGTM 🚀

2023-01-17 14:00 UTC, polvorin approved these changes

2023-01-17 14:03 UTC, merged