[shell-global-defaults]
build-trust/ockam pull request #4169
Opened 2023-01-31 19:00 UTC by Miidoriya

Removed runs-on from job and created defaults block for ubuntu-20.04

## Current Behavior

Shell is set within each job of the documentation.yml
- At present there is one job but in the future there may be more

## Proposed Changes

Change to abstract the shell each job runs on into a global defaults block
- allows less repetition of code when future jobs are created which use the same shell to run on

## Checks

- [X] All commits in this Pull Request are [signed](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) and Verified by Github.
- [X] All commits in this Pull Request follow the Ockam [commit message convention](https://github.com/build-trust/.github/blob/main/CONTRIBUTING.md#commit-messages).
- [X] I accept the Ockam Community [Code of Conduct](https://github.com/build-trust/.github/blob/main/CODE_OF_CONDUCT.md).
- [X] I have accepted the Ockam [Contributor License Agreement](https://github.com/build-trust/ockam-contributors/blob/main/CLA.md) by adding my Git/Github details in a row at the end of the [CONTRIBUTORS.csv](https://github.com/build-trust/ockam-contributors/blob/main/CONTRIBUTORS.csv) file in a separate pull request to the [build-trust/ockam-contributors](https://github.com/build-trust/ockam-contributors) repository.

2023-01-31 20:23 UTC, metaclips commented
@Miidoriya can you update your commit message to `ci: set global shell default for documentation.yml`
```bash
git reset HEAD^1
# Right after calling the reset command, you can update your code with
# the suggested reviews then run the below commands
git add .github/workflows/documentation.yml
git commit -S -m "ci: set global shell default for documentation.yml"
git push -f
```

2023-01-31 20:55 UTC, Miidoriya commented
@metaclips commit message has been updated :)

2023-02-02 10:12 UTC, metaclips commented
> @metaclips commit message has been updated :)

Thanks @Miidoriya. Can you also look at reviews comments, there are little changes we need to make.

2023-02-02 16:47 UTC, Miidoriya commented
Hey @metaclips , which comment would this be? I can only see the comment around updating the commit message which has been done

2023-02-02 16:50 UTC, metaclips requested changes
Hey @Miirdoriya 😄 I missed submitting this review, apologies, little changes for a merge 🥶

2023-02-02 16:50 UTC, metaclips commented on .github/workflows/documentation.yml
> +    runs-on: ubuntu-20.04
We want to set default shell only 
```yaml
runs-on: ubuntu-20.04
```
Should be
```yaml
shell: bash
```

2023-02-02 16:50 UTC, metaclips commented on .github/workflows/documentation.yml
> -    runs-on: ubuntu-20.04
Let's add this back

2023-02-02 16:53 UTC, Miidoriya commented on .github/workflows/documentation.yml
> +    runs-on: ubuntu-20.04
Gotcha. Will make this change now

2023-02-02 16:55 UTC, Miidoriya commented
@metaclips that change should be in now

2023-02-02 17:00 UTC, mrinalwadhwa commented
Thank you for spending time on this, before we can merge please

- [ ] Accept the Ockam [Contributor License Agreement](https://github.com/build-trust/ockam-contributors/blob/main/CLA.md) by adding your Git/Github details in a row at the end of the [CONTRIBUTORS.csv](https://github.com/build-trust/ockam-contributors/blob/main/CONTRIBUTORS.csv) file in a separate pull request to the [build-trust/ockam-contributors](https://github.com/build-trust/ockam-contributors) repository.

The easiest way to do this is to [edit the CONTRIBUTORS.csv](https://github.com/build-trust/ockam-contributors/edit/main/CONTRIBUTORS.csv) file in the github web UI and create a PR, this will make the commit as verified.

2023-02-02 17:03 UTC, Miidoriya commented
Hey @mrinalwadhwa , That PR has been created https://github.com/build-trust/ockam-contributors/pull/180

2023-02-02 17:55 UTC, metaclips commented on .github/workflows/documentation.yml
> +    runs-on: ubuntu-20.04
Can you confirm you made the change, it shows `runs-on: bash` on my end.

2023-02-02 18:17 UTC, Miidoriya commented on .github/workflows/documentation.yml
> +    runs-on: ubuntu-20.04
That should be updated now

2023-02-02 18:33 UTC, metaclips commented on .github/workflows/documentation.yml
> +    runs-on: ubuntu-20.04
Nice. Thanks

2023-02-02 18:47 UTC, metaclips approved these changes, later dismissed
Thanks for an amazing PR @Miidoriya

2023-02-02 19:11 UTC, metaclips approved these changes
Thanks again @Miidoriya

2023-02-02 20:37 UTC, mrinalwadhwa approved these changes

2023-02-02 20:38 UTC, merged

2023-02-02 20:38 UTC, mrinalwadhwa commented
@Miidoriya thank you and congratulations on an awesome first contribution 🥳