feat(rust): move SocketAddrV4 parsing of TransportStatus as an intern…
build-trust/ockam pull request #4408
Opened 2023-03-06 15:46 UTC by hugoamalric

…al method

## Current behavior

In some commands, the TransportStatus socket_addr field is parsed manually.

## Proposed changes

Added a method to the TransportStatus struct to do that parsing.

## Checks

- [ ] All commits in this Pull Request are [signed](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) and Verified by Github.
- [ ] All commits in this Pull Request follow the Ockam [commit message convention](https://github.com/build-trust/.github/blob/main/CONTRIBUTING.md#commit-messages).
- [ ] I accept the Ockam Community [Code of Conduct](https://github.com/build-trust/.github/blob/main/CODE_OF_CONDUCT.md).
- [ ] I have accepted the Ockam [Contributor License Agreement](https://github.com/build-trust/ockam-contributors/blob/main/CLA.md) by adding my Git/Github details in a row at the end of the [CONTRIBUTORS.csv](https://github.com/build-trust/ockam-contributors/blob/main/CONTRIBUTORS.csv) file in a separate pull request to the [build-trust/ockam-contributors](https://github.com/build-trust/ockam-contributors) repository. The easiest way to do this is to [edit the CONTRIBUTORS.csv](https://github.com/build-trust/ockam-contributors/edit/main/CONTRIBUTORS.csv) file in the github web UI and create a PR, this will mark the commit as verified.

2023-03-09 08:22 UTC, adrianbenavides requested changes
Hey @hugoamalric, thanks for making your first contribution! It looks pretty great, I just left a small comment regarding how we handle errors.

To pass the CI checks you will have to:
- Amend your commit message to not include caps or write those words between "\`", like \`TransportStatus\`
- Run `cargo fmt` to fix format issues
- Run `cargo clippy` and fix potential lint issues

2023-03-09 08:22 UTC, adrianbenavides commented on implementations/rust/ockam/ockam_api/src/nodes/models/transport.rs
> +    pub fn socket_addr(&self) -> std::result::Result<SocketAddrV4, AddrParseError> {
This should return an `ockam_core::Result`, manually mapping the `AddrParseError` into an `ockam_core::Error`.

2023-03-09 08:22 UTC, adrianbenavides commented on implementations/rust/ockam/ockam_command/src/tcp/connection/create.rs
> +                let to = response.socket_addr().map_err(|_| {
Related to the other comment, if `socket_addr` returns an ockam_core::Error, then you could leave this unmodified.

2023-03-10 09:30 UTC, adrianbenavides approved these changes
Looks perfect now, thanks @hugoamalric and congratulations on your first contribution to Ockam! 🥳 

It will get merged after today's release.

2023-03-14 09:08 UTC, adrianbenavides commented
Hey @hugoamalric, we'll merge your PR today. Before that, we need you to accepted the Ockam Contributor License Agreement:

> I have accepted the Ockam [Contributor License Agreement](https://github.com/build-trust/ockam-contributors/blob/main/CLA.md) by adding my Git/Github details in a row at the end of the [CONTRIBUTORS.csv](https://github.com/build-trust/ockam-contributors/blob/main/CONTRIBUTORS.csv) file in a separate pull request to the [build-trust/ockam-contributors](https://github.com/build-trust/ockam-contributors) repository. The easiest way to do this is to [edit the CONTRIBUTORS.csv](https://github.com/build-trust/ockam-contributors/edit/main/CONTRIBUTORS.csv) file in the github web UI and create a PR, this will mark the commit as verified.

2023-03-14 09:18 UTC, hugoamalric commented
@adrianbenavides I have already accepted the CLA, but it doesn't detect the same email for some reason

2023-03-14 15:29 UTC, adrianbenavides commented
> @adrianbenavides I have already accepted the CLA, but it doesn't detect the same email for some reason
> 
> Edited in : [build-trust/ockam-contributors#192](https://github.com/build-trust/ockam-contributors/pull/192)

Ready now, thanks again @hugoamalric 💪

2023-03-14 15:30 UTC, adrianbenavides approved these changes

2023-03-14 15:42 UTC, merged