feat(rust): initialize the credential example with a change history and the latest key
build-trust/ockam pull request #4431
Opened 2023-03-08 17:36 UTC by etorreborre

WIP

2023-03-09 09:48 UTC, SanjoDeundiak commented on examples/rust/get_started/examples/06-credentials-exchange-alice.rs
> +    let secret = "41b6873b20d95567bf958e6bab2808e9157720040882630b1bb37a72f4015cd2";
Maybe user should import the secret here manually to the vault?

2023-03-10 09:28 UTC, etorreborre commented
@mrinalwadhwa are you ok with these changes?

2023-03-10 16:18 UTC, SanjoDeundiak approved these changes, later dismissed

2023-03-10 16:46 UTC, mrinalwadhwa requested changes
@etorreborre left some comment for minor renames for the identity related words.

2023-03-10 16:46 UTC, mrinalwadhwa commented on examples/rust/get_started/examples/06-credentials-exchange-client.rs
> +    let identity_history = "01dcf392551f796ef1bcb368177e53f9a5875a962f67279259207d24a01e690721000547c93239ba3d818ec26c9cdadd2a35cbdf1fa3b6d1a731e06164b1079fb7b8084f434b414d5f524b03012000000020a0d205f
let's change this variable's name to `change_history`

2023-03-10 16:46 UTC, mrinalwadhwa commented on examples/rust/get_started/examples/06-credentials-exchange-client.rs
> +    let client = Identity::create_identity_with_history(&ctx, vault, identity_history, secret).await?;
let's rename the function `create_identity_with_history` to `create_identity_with_change_history`

2023-03-10 16:46 UTC, mrinalwadhwa commented on examples/rust/get_started/examples/06-credentials-exchange-issuer.rs
>  ///
Let's remove the comment at the top of this file.

2023-03-10 16:46 UTC, mrinalwadhwa commented on examples/rust/get_started/examples/06-credentials-exchange-server.rs
> +    let identity_history = "01ed8a5b1303f975c1296c990d1bd3c1946cfef328de20531e3511ec5604ce0dd9000547c93239ba3d818ec26c9cdadd2a35cbdf1fa3b6d1a731e06164b1079fb7b8084f434b414d5f524b03012000000020e8c328b
identity_history to change_history

2023-03-10 16:46 UTC, mrinalwadhwa commented on examples/rust/get_started/examples/06-credentials-exchange-server.rs
> +    let server = Identity::create_identity_with_history(&ctx, vault, identity_history, secret).await?;
create_identity_with_history to create_identity_with_change_history

2023-03-10 17:11 UTC, mrinalwadhwa approved these changes

2023-03-10 17:30 UTC, merged