feat: adding show command, to show details of listener
build-trust/ockam pull request #4455
Opened 2023-03-13 15:19 UTC by 0xkelvin

## Current behavior

## Proposed changes

## Checks

- [x] All commits in this Pull Request are [signed](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) and Verified by Github.
- [x] All commits in this Pull Request follow the Ockam [commit message convention](https://github.com/build-trust/.github/blob/main/CONTRIBUTING.md#commit-messages).
- [x] I accept the Ockam Community [Code of Conduct](https://github.com/build-trust/.github/blob/main/CODE_OF_CONDUCT.md).
- [x] I have accepted the Ockam [Contributor License Agreement](https://github.com/build-trust/ockam-contributors/blob/main/CLA.md) by adding my Git/Github details in a row at the end of the [CONTRIBUTORS.csv](https://github.com/build-trust/ockam-contributors/blob/main/CONTRIBUTORS.csv) file in a separate pull request to the [build-trust/ockam-contributors](https://github.com/build-trust/ockam-contributors) repository. The easiest way to do this is to [edit the CONTRIBUTORS.csv](https://github.com/build-trust/ockam-contributors/edit/main/CONTRIBUTORS.csv) file in the github web UI and create a PR, this will mark the commit as verified.

2023-03-17 09:42 UTC, 0xkelvin commented
this PR is the implementation for this https://github.com/build-trust/ockam/issues/4419

2023-03-17 10:48 UTC, adrianbenavides commented
> this PR is the implementation for this #4419

A small tip: if you write "Fix {url of the issue}" in the PR description it gets automatically linked (you will see it in the `Development` section on the right sidebar.

2023-03-17 11:06 UTC, adrianbenavides requested changes
Thanks @0xkelvin! It looks great so far, but there a couple of parts missing:
- Implement the NodeManager endpoint.
- Add a bats test

2023-03-17 11:06 UTC, adrianbenavides commented on implementations/rust/ockam/ockam_command/src/tcp/listener/show.rs
> +    rpc.request(Request::get("/node/tcp/listener")).await?;
You have to add a new endpoint to the NodeManager to respond to this new request. Note that the endpoint must include the `id` of the tcp-listener you want to retrieve.

Check this PR as an example: https://github.com/build-trust/ockam/pull/4446

2023-03-17 11:06 UTC, adrianbenavides commented on implementations/rust/ockam/ockam_command/src/tcp/listener/show.rs
> +}
You can simplify this and inline the `at` argument within the `ShowCommand` struct.

2023-03-28 04:50 UTC, adrianbenavides approved these changes

2023-03-28 05:39 UTC, merged