feat: shutting down when delete listener node
build-trust/ockam pull request #4473
Opened 2023-03-16 12:41 UTC by 0xkelvin

## Current behavior

## Proposed changes

## Checks

- [ ] All commits in this Pull Request are [signed](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) and Verified by Github.
- [ ] All commits in this Pull Request follow the Ockam [commit message convention](https://github.com/build-trust/.github/blob/main/CONTRIBUTING.md#commit-messages).
- [ ] I accept the Ockam Community [Code of Conduct](https://github.com/build-trust/.github/blob/main/CODE_OF_CONDUCT.md).
- [ ] I have accepted the Ockam [Contributor License Agreement](https://github.com/build-trust/ockam-contributors/blob/main/CLA.md) by adding my Git/Github details in a row at the end of the [CONTRIBUTORS.csv](https://github.com/build-trust/ockam-contributors/blob/main/CONTRIBUTORS.csv) file in a separate pull request to the [build-trust/ockam-contributors](https://github.com/build-trust/ockam-contributors) repository. The easiest way to do this is to [edit the CONTRIBUTORS.csv](https://github.com/build-trust/ockam-contributors/edit/main/CONTRIBUTORS.csv) file in the github web UI and create a PR, this will mark the commit as verified.

2023-03-17 09:35 UTC, adrianbenavides commented
Hey @0xkelvin, thanks for submitting another PR! Could you link the issue that this PR solves and add some description to it?

2023-03-17 09:40 UTC, 0xkelvin commented
> Hey @0xkelvin, thanks for submitting another PR! Could you link the issue that this PR solves and add some description to it?

the PR is for https://github.com/build-trust/ockam/issues/4367
the expectation behaviour is the handler should shutdown the listener node when it got deleted 

cc : @adrianbenavides

2023-03-17 11:12 UTC, adrianbenavides commented on implementations/rust/ockam/ockam_command/tests/bats/unit.bats
You should add a new test, just as the `tcp connection - CRUD` but using the `listener` commands.

2023-03-17 11:12 UTC, adrianbenavides commented on implementations/rust/ockam/ockam_api/src/nodes/service/transport.rs
> +                // warn!("It is not currently supported to destroy LISTEN transports");
You can remove this line if it's no longer needed.

2023-03-17 11:12 UTC, adrianbenavides requested changes
Looks great @0xkelvin ! Just a small comment about how to improve the test

2023-03-28 04:50 UTC, adrianbenavides approved these changes

2023-03-28 05:53 UTC, adrianbenavides commented
For some reason, the https://github.com/build-trust/ockam/pull/4455 PR got merged before this one although this was added first to the merge queue. https://github.com/build-trust/ockam/pull/4455 includes the commits of the current PR, so I'm closing this one.

2023-03-28 05:53 UTC, closed without merging