add clap command to show secure-channel listener
build-trust/ockam pull request #4515
Opened 2023-03-22 14:32 UTC by murex971

Resolves #4439

2023-03-22 20:14 UTC, davide-baldo requested changes
Thanks for your contribution!
it looks fantastic :+1:  only minor changes are required!

2023-03-22 20:14 UTC, davide-baldo commented on implementations/rust/ockam/ockam_api/src/nodes/models/secure_channel.rs
> +    #[n(0)] tag: TypeTag<8293631>,
the cbor encoding is perfect! but the random number of the `TypeTag` is already taken by another structure. Could you please change the number with a new random number?

You can use this generator: https://www.random.org/integers/?num=100&min=1000000&max=9999999&col=5&base=10&format=html&rnd=new

2023-03-22 20:14 UTC, davide-baldo commented on implementations/rust/ockam/ockam_api/src/nodes/models/secure_channel.rs
> +    #[n(0)] tag: TypeTag<8642885>,
Same as before, everything looks good, only the `TypeTag` random needs an update.

2023-03-22 20:14 UTC, davide-baldo commented on implementations/rust/ockam/ockam_command/src/secure_channel/listener/show.rs
> +        "secure-channel listener with address '/service/{}'",
Could you please simplify the output to align it to the creation command?

https://github.com/build-trust/ockam/blob/develop/implementations/rust/ockam/ockam_command/src/secure_channel/listener/create.rs#L73

2023-03-22 20:14 UTC, davide-baldo commented on implementations/rust/ockam/ockam_command/src/secure_channel/listener/mod.rs
> +    #[command(display_order = 800)]
Seems like every command wants to be displayed with the same priority! :smile: 
`display_order` should be incremental, smaller numbers are displayed before others.
Would you do me the favor to update also previously existing `display_order` from 800 to 803?

2023-03-23 08:29 UTC, murex971 commented
@davide-baldo  thanks for the review. 
Made all the changes :)

2023-03-24 14:53 UTC, davide-baldo approved these changes, later dismissed
nice! :+1: 
I can't merge right away due to an upcoming release, but we'll merge as soon as we can!

2023-03-27 14:55 UTC, etorreborre approved these changes, later dismissed

2023-03-27 14:57 UTC, SanjoDeundiak approved these changes

2023-03-27 15:21 UTC, merged