issue#4637:dprint
build-trust/ockam pull request #4723
Opened 2023-04-15 15:20 UTC by itsajay1029

## Current behavior

Added `dprint` for formatting of the Cargo.toml files and also created github actions for it so that everytime someone commit changes to the codebase, the code automatically get formatted properly.

## Proposed changes

## Checks

- [x] All commits in this Pull Request are [signed](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) and Verified by Github.
- [x] All commits in this Pull Request follow the Ockam [commit message convention](https://github.com/build-trust/.github/blob/main/CONTRIBUTING.md#commit-messages).
- [x] I accept the Ockam Community [Code of Conduct](https://github.com/build-trust/.github/blob/main/CODE_OF_CONDUCT.md).
- [x] I have accepted the Ockam [Contributor License Agreement](https://github.com/build-trust/ockam-contributors/blob/main/CLA.md) by adding my Git/Github details in a row at the end of the [CONTRIBUTORS.csv](https://github.com/build-trust/ockam-contributors/blob/main/CONTRIBUTORS.csv) file in a separate pull request to the [build-trust/ockam-contributors](https://github.com/build-trust/ockam-contributors) repository. The easiest way to do this is to [edit the CONTRIBUTORS.csv](https://github.com/build-trust/ockam-contributors/edit/main/CONTRIBUTORS.csv) file in the github web UI and create a PR, this will mark the commit as verified.

2023-04-15 15:48 UTC, metaclips requested changes
Thanks for an amazing PR @itsajay1029 🎉 little changes left to get the PR merged. 
- CI requires we format our files accordingly, [and fails if we don't](https://github.com/build-trust/ockam/actions/runs/4708494194/jobs/8350972731?pr=4723#step:4:7), can we remove the whitespaces added?
- We follow certain rules when creating commit message, rules are stated [here](https://github.com/build-trust/ockam/actions/runs/4708494194/jobs/8350972731?pr=4723#step:4:7), can we rename the commit message to `ci: add workflow that lints cargo.toml files`

2023-04-15 15:48 UTC, metaclips commented on .github/workflows/all.yml
> +        run: sudo snap install dprint
We can't install dprint with `snap` as it fails in CI, logs here https://github.com/build-trust/ockam/actions/runs/4708494194/jobs/8350973001?pr=4723#step:3:5. Can we instead use npm `npm install -g dprint`?

2023-04-15 15:48 UTC, metaclips commented on .github/workflows/all.yml
> +          dprint fmt
No need to apply formatting, `dprint check` should be just fine.

2023-04-15 15:48 UTC, metaclips commented on .github/workflows/all.yml
> +        uses: actions/checkout@v2
Let's pin the version of `actions/checkout` 
actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab

2023-04-15 17:15 UTC, itsajay1029 commented
Made all the changes @metaclips needed

2023-04-15 18:04 UTC, metaclips submitted a review, later dismissed
We missed a whitespace in the JSON file, also can we squash commits into 1?, here's how I'll do that
```bash
git reset origin/develop
git add --all
git commit -S -m "ci: add workflow that lints cargo.toml files"
git push -f
```

2023-04-15 18:04 UTC, metaclips commented on dprint.json
> +}
Let's remove the whitespace here [so that CI will pass](https://github.com/build-trust/ockam/actions/runs/4708951216/jobs/8351742648?pr=4723)

2023-04-15 18:34 UTC, itsajay1029 commented on dprint.json
> +}
I cannot spot the white space @metaclips

2023-04-15 19:11 UTC, mrinalwadhwa commented on dprint.json
> +}
Different editors have setting typically called "Show invisibles" that can be very useful for this for example https://stackoverflow.com/questions/30140595/show-whitespace-characters-in-visual-studio-code

2023-04-15 19:11 UTC, mrinalwadhwa commented
@itsajay1029 Thank you for spending time on this, before we can merge please:

- [ ] Accept the Ockam [Contributor License Agreement](https://github.com/build-trust/ockam-contributors/blob/main/CLA.md) by adding your Git/Github details in a row at the end of the [CONTRIBUTORS.csv](https://github.com/build-trust/ockam-contributors/blob/main/CONTRIBUTORS.csv) file in a separate pull request to the [build-trust/ockam-contributors](https://github.com/build-trust/ockam-contributors) repository.

The easiest way to do this is to [edit the CONTRIBUTORS.csv](https://github.com/build-trust/ockam-contributors/edit/main/CONTRIBUTORS.csv) file in the github web UI and create a PR, this will make the commit as verified.

2023-04-15 19:44 UTC, itsajay1029 commented
> @itsajay1029 Thank you for spending time on this, before we can merge please:
> 
> * [ ]  Accept the Ockam [Contributor License Agreement](https://github.com/build-trust/ockam-contributors/blob/main/CLA.md) by adding your Git/Github details in a row at the end of the [CONTRIBUTORS.csv](https://github.com/build-trust/ockam-contributors/blob/main/CONTRIBUTORS.csv) file in a separate pull request to the [build-trust/ockam-contributors](https://github.com/build-trust/ockam-contributors) repository.
> 
> The easiest way to do this is to [edit the CONTRIBUTORS.csv](https://github.com/build-trust/ockam-contributors/edit/main/CONTRIBUTORS.csv) file in the github web UI and create a PR, this will make the commit as verified.

Sure I will add my name to the CONTRIBUTORS.csv file after it is merged successfully

2023-04-16 16:45 UTC, itsajay1029 commented
I have accepted the Ockam CLA. Please review this PR @mrinalwadhwa @metaclips

2023-04-16 17:31 UTC, metaclips commented
> I have accepted the Ockam CLA. Please review this PR @mrinalwadhwa @metaclips

Nice 🕺🏽. Let's squash all commits again so that we can merge
```bash
git reset origin/develop
git add --all
git commit -S -m "ci: add workflow that lints cargo.toml files"
git pull --rebase origin develop
git push -f
```
We need to ensure the commit is signed by calling the `-S` flag in `git commit -S -m "ci: add workflow that lints cargo.toml files"`.

2023-04-16 18:49 UTC, itsajay1029 commented
> > I have accepted the Ockam CLA. Please review this PR @mrinalwadhwa @metaclips
> 
> Nice 🕺🏽. Let's squash all commits again so that we can merge
> 
> ```shell
> git reset origin/develop
> git add --all
> git commit -S -m "ci: add workflow that lints cargo.toml files"
> git pull --rebase origin develop
> git push -f
> ```
> 
> We need to ensure the commit is signed by calling the `-S` flag in `git commit -S -m "ci: add workflow that lints cargo.toml files"`.

I am getting an error : 
![image](https://user-images.githubusercontent.com/77872387/232335027-4740e9c5-9ce2-4488-9915-66ef5bdc4a6e.png)

2023-04-17 12:21 UTC, metaclips commented
> > > I have accepted the Ockam CLA. Please review this PR @mrinalwadhwa @metaclips
> > 
> > 
> > Nice 🕺🏽. Let's squash all commits again so that we can merge
> > ```shell
> > git reset origin/develop
> > git add --all
> > git commit -S -m "ci: add workflow that lints cargo.toml files"
> > git pull --rebase origin develop
> > git push -f
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > We need to ensure the commit is signed by calling the `-S` flag in `git commit -S -m "ci: add workflow that lints cargo.toml files"`.
> 
> I am getting an error @metaclips : ![image](https://user-images.githubusercontent.com/77872387/232335027-4740e9c5-9ce2-4488-9915-66ef5bdc4a6e.png)

@itsajay1029 I squashed commits on my end. We can continue discussion on signing commits with Git on this PR, here's a link from GitHub on creating signed commits on multiple OSs, including windows https://docs.github.com/en/authentication/managing-commit-signature-verification/about-commit-signature-verification#gpg-commit-signature-verification. Please ask here (even when the PR is merged) if you have any question or if signed commits works for youi.

2023-04-17 12:22 UTC, SanjoDeundiak approved these changes

2023-04-17 12:35 UTC, merged

2023-04-17 13:08 UTC, metaclips commented
Thanks for an amazing PR @itsajay1029