Jamesneb/refactor starts with
build-trust/ockam pull request #4738
Opened 2023-04-17 23:46 UTC by jamesneb

## Current behavior

The starts_with_* methods return the index at which a split should be applied.
## Proposed changes

starts_with_* methods now perform the split automatically and return a pair of MultiAddresses.

## Checks

- [ ] All commits in this Pull Request are [signed](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) and Verified by Github.
- [ ] All commits in this Pull Request follow the Ockam [commit message convention](https://github.com/build-trust/.github/blob/main/CONTRIBUTING.md#commit-messages).
- [ ] I accept the Ockam Community [Code of Conduct](https://github.com/build-trust/.github/blob/main/CODE_OF_CONDUCT.md).
- [ ] I have accepted the Ockam [Contributor License Agreement](https://github.com/build-trust/ockam-contributors/blob/main/CLA.md) by adding my Git/Github details in a row at the end of the [CONTRIBUTORS.csv](https://github.com/build-trust/ockam-contributors/blob/main/CONTRIBUTORS.csv) file in a separate pull request to the [build-trust/ockam-contributors](https://github.com/build-trust/ockam-contributors) repository. The easiest way to do this is to [edit the CONTRIBUTORS.csv](https://github.com/build-trust/ockam-contributors/edit/main/CONTRIBUTORS.csv) file in the github web UI and create a PR, this will mark the commit as verified.

2023-04-21 18:22 UTC, CAOakleyII requested changes, later dismissed
Thank you for your first contribution! 🎉 Welcome to the community!

Overall the PR looks good, just a few minor things to fix up.

2023-04-21 18:22 UTC, CAOakleyII commented on implementations/rust/ockam/ockam_api/src/session/util.rs
> +        Some(addr.split(1))
This should still stick with the index of 2.

When we split a TCP, we need both the IP address and Port

An example multi_addr would be`/dnsaddr/localhost/tcp/4000/service/api`, the tcp address is `/dnsaddr/localhost/tcp/4000` (localhost:4000) and the remaining part of the address is `/service/api`

2023-04-21 18:22 UTC, CAOakleyII commented on implementations/rust/ockam/ockam_api/src/session/util.rs
> +        assert!(m1.to_string() != m2.to_string());
We can improve this test a little with checking for the correct starting address, and then the remaining address.

Keeping from the example above - `/dnsaddr/localhost/tcp/4000/service/api`

m1 -> `/dnsaddr/localhost/tcp/4000`

m2 -> `/service/api`

2023-04-21 18:24 UTC, CAOakleyII commented
One more thing to note is our commit linter rules.

In order to maintain a linear commit history we require rebases instead of merges. This will require you to either change the commit history of this PR, or you can create a new PR if you'd like to start fresh from there.

2023-04-21 22:49 UTC, jamesneb commented
Woo! This was my first rebase, I think it went correctly.

2023-04-28 15:17 UTC, davide-baldo commented
I've aligned, merging soon! :+1:

2023-04-29 02:29 UTC, adrianbenavides approved these changes

2023-04-29 05:37 UTC, merged