feat(rust): adding rotate-key to ockam_command cli
build-trust/ockam pull request #4876
Opened 2023-05-05 02:34 UTC by noyez

This commit adds the rotate-key command to the CLI. It can be used via `ockam identity rotate-key --node n1 --label OCKAM_RK` or the label argument can be omitted to use the default label of "OCKAM_RK", e.g. `ockam identity rotate-key --node n1`.

In response to issue: https://github.com/build-trust/ockam/issues/3685

This is a replacement for https://github.com/build-trust/ockam/pull/3841

## Current Behavior

`ockam identity rotate-key` did not exists.

## Proposed Changes

create cli command `ockam identity rotate-key`

## Checks

- [x] All commits in this Pull Request are [signed](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) and Verified by Github.
- [x] All commits in this Pull Request follow the Ockam [commit message convention](https://github.com/build-trust/.github/blob/main/CONTRIBUTING.md#commit-messages).
- [x] I accept the Ockam Community [Code of Conduct](https://github.com/build-trust/.github/blob/main/CODE_OF_CONDUCT.md).
- [x] I have accepted the Ockam [Contributor License Agreement](https://github.com/build-trust/ockam-contributors/blob/main/CLA.md) by adding my Git/Github details in a row at the end of the [CONTRIBUTORS.csv](https://github.com/build-trust/ockam-contributors/blob/main/CONTRIBUTORS.csv) file in a separate pull request to the [build-trust/ockam-contributors](https://github.com/build-trust/ockam-contributors) repository. The easiest way to do this is to [edit the CONTRIBUTORS.csv](https://github.com/build-trust/ockam-contributors/edit/main/CONTRIBUTORS.csv) file in the github web UI and create a PR, this will mark the commit as verified.

2023-05-10 16:54 UTC, SanjoDeundiak requested changes
Nice job! Have few comments

2023-05-10 16:54 UTC, SanjoDeundiak commented on implementations/rust/ockam/ockam_command/src/identity/rotate_key.rs
> +    label: String,
Do you think this argument could be optional so we can use the default value where we handle this request?

2023-05-10 16:54 UTC, SanjoDeundiak commented on implementations/rust/ockam/ockam_command/src/identity/rotate_key.rs
> +    // XXX Should this be post?
I think that's correct

2023-05-10 16:54 UTC, SanjoDeundiak commented on implementations/rust/ockam/ockam_command/tests/bats/unit.bats
> +@test "create a node and show its identity then rotate keys" {
Could you please look why this test doesn't pass?

2023-05-10 16:54 UTC, SanjoDeundiak commented on implementations/rust/ockam/ockam_api/src/nodes/service/transport.rs
> +    pub(super) async fn rotate_key<'a>(
I think this function should be placed inside the `node_identities.rs` or have a dedicated file, like `identity.rs`

2023-05-10 16:54 UTC, SanjoDeundiak commented on implementations/rust/ockam/ockam_api/src/nodes/service/transport.rs
> +        let identity = &mut node_manager.identity();
`NodeManager::identity()` returns a clone of the `Identity` struct, so this rotate call won't actually change anything on NodeManager's Identity

2023-05-10 16:54 UTC, SanjoDeundiak commented on implementations/rust/ockam/ockam_api/src/nodes/service/transport.rs
> +        let identity = &mut node_manager.identity();
Do you think we could access the field directly here?

2023-05-10 16:54 UTC, SanjoDeundiak commented on implementations/rust/ockam/ockam_api/src/nodes/service.rs
> +    async fn handle_request<'a>(
Why is this change required?

2023-05-10 16:54 UTC, SanjoDeundiak commented on implementations/rust/ockam/ockam/src/node.rs
> +    /*
Could you please remove it?

2023-05-10 16:54 UTC, SanjoDeundiak requested changes
Nice job! Have few comments

2023-05-23 07:28 UTC, etorreborre commented
Hi @noyez! Do you need any help for completing this PR?

2023-05-24 00:43 UTC, noyez commented
I think i need to pull in some code from master to get the tests passing. My dev machine is on the fritz and so i've been trying to get to get it to boot again.

2023-06-06 12:35 UTC, davide-baldo commented
Your work is much appreciated! Is there anything we can do to support you in completing this task?

2023-06-08 13:45 UTC, etorreborre commented on implementations/rust/ockam/ockam_command/src/identity/rotate_key.rs
> +    label: String,
I am actually not concerned that we could infer a default value. I am more concerned by the fact that there is no argument to select a specific identity :-).

I would actually not use `node` as an argument for the command but rather `identity` since when you create an identity you don't specify a node. The other argument which should also be added IMO is `vault` since you can specify a specific vault when creating an identity.

2023-06-08 20:10 UTC, noyez commented on implementations/rust/ockam/ockam_api/src/nodes/service.rs
> +    async fn handle_request<'a>(
This was puzzling to me too. w/o it i received this compile error. 

```error: lifetime may not live long enough
   --> implementations/rust/ockam/ockam_api/src/nodes/service.rs:572:17
    |
535 |         req: &Request<'_>,
    |                       -- let's call the lifetime of this reference `'1`
536 |         dec: &mut Decoder<'_>,
    |                           -- let's call the lifetime of this reference `'2`
...
572 |                 self.rotate_key(req, dec).await?.to_vec()?
    |                 ^^^^^^^^^^^^^^^^^^^^^^^^^ argument requires that `'1` must outlive `'2`
    ```

2023-06-08 20:11 UTC, noyez commented on implementations/rust/ockam/ockam_api/src/nodes/service/transport.rs
> +        let identity = &mut node_manager.identity();
i rebased on develop, It looks like NodeManager::Identity() no long exists, so this will have to be reworked anyway.

2023-06-08 20:13 UTC, noyez commented on implementations/rust/ockam/ockam_command/src/identity/rotate_key.rs
> +    label: String,
@SanjoDeundiak which argument do you mean? 

@etorreborre Oh, ok. I thought that a node always has to be running and that held the identity.

2023-08-23 08:35 UTC, etorreborre commented
@SanjoDeundiak what is the impact of the identity v2 work for this PR? Just a minor change to use a new API for identities?

2023-08-23 09:20 UTC, SanjoDeundiak commented
@etorreborre should not be a significant change. It's OK to merge this PR when it's ready

2023-12-08 13:19 UTC, closed without merging