feat(rust): environment command & moved text
build-trust/ockam pull request #4958
Opened 2023-05-21 04:36 UTC by Neruelin

## Current behavior

Information about Environment Variables is displayed in the footers of other commands taking up a large space.

## Proposed changes

Created a new 'environment' CLI command to display the Environment Variables information separately, and removed the moved text from the other CLI footer.

## Checks

- [✅] All commits in this Pull Request are [signed](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) and Verified by Github.
- [✅] All commits in this Pull Request follow the Ockam [commit message convention](https://github.com/build-trust/.github/blob/main/CONTRIBUTING.md#commit-messages).
- [✅] I accept the Ockam Community [Code of Conduct](https://github.com/build-trust/.github/blob/main/CODE_OF_CONDUCT.md).
- [✅] I have accepted the Ockam [Contributor License Agreement](https://github.com/build-trust/ockam-contributors/blob/main/CLA.md) by adding my Git/Github details in a row at the end of the [CONTRIBUTORS.csv](https://github.com/build-trust/ockam-contributors/blob/main/CONTRIBUTORS.csv) file in a separate pull request to the [build-trust/ockam-contributors](https://github.com/build-trust/ockam-contributors) repository. The easiest way to do this is to [edit the CONTRIBUTORS.csv](https://github.com/build-trust/ockam-contributors/edit/main/CONTRIBUTORS.csv) file in the github web UI and create a PR, this will mark the commit as verified.

2023-05-21 04:53 UTC, mrinalwadhwa commented
@Neruelin Thank you for spending time on this, before we can merge please

- [ ] Accept the Ockam [Contributor License Agreement](https://github.com/build-trust/ockam-contributors/blob/main/CLA.md) by adding your Git/Github details in a row at the end of the [CONTRIBUTORS.csv](https://github.com/build-trust/ockam-contributors/blob/main/CONTRIBUTORS.csv) file in a separate pull request to the [build-trust/ockam-contributors](https://github.com/build-trust/ockam-contributors) repository.

The easiest way to do this is to [edit the CONTRIBUTORS.csv](https://github.com/build-trust/ockam-contributors/edit/main/CONTRIBUTORS.csv) file in the github web UI and create a PR, this will make the commit as verified.

2023-05-21 08:37 UTC, Neruelin commented
> @Neruelin Thank you for spending time on this, while we review please
> 
> * [ ]  Accept the Ockam [Contributor License Agreement](https://github.com/build-trust/ockam-contributors/blob/main/CLA.md) by adding your Git/Github details in a row at the end of the [CONTRIBUTORS.csv](https://github.com/build-trust/ockam-contributors/blob/main/CONTRIBUTORS.csv) file in a separate pull request to the [build-trust/ockam-contributors](https://github.com/build-trust/ockam-contributors) repository.
> 
> The easiest way to do this is to [edit the CONTRIBUTORS.csv](https://github.com/build-trust/ockam-contributors/edit/main/CONTRIBUTORS.csv) file in the github web UI and create a PR, this will make the commit as verified.

Created the contributors PR
https://github.com/build-trust/ockam-contributors/pull/216

2023-05-22 18:17 UTC, adrianbenavides requested changes, later dismissed
Thanks for submitting another PR @Neruelin, just two small fixes before we can merge it 👍

2023-05-22 18:17 UTC, adrianbenavides commented on implementations/rust/ockam/ockam_command/src/environment/mod.rs
> +
You could add a short documentation line for the command like: `Show the Ockam environment variables`

2023-05-22 18:17 UTC, adrianbenavides commented on implementations/rust/ockam/ockam_command/src/environment/static/envtext.txt
> +
These two lines are not needed anymore.

2023-05-23 08:09 UTC, adrianbenavides approved these changes
LGTM! Congrats @Neruelin for landing your first PR at ockam 🥳

2023-05-23 08:28 UTC, merged