ci: created ockam-artifact.yml
build-trust/ockam pull request #5073
Opened 2023-06-06 11:33 UTC by rghdrizzle

This PR solves the issue #4639 
So I created a workflow to build artifact image of ockam command everytime when there is a change in implementations/rust/ockam path , after building the image , the workflow pushes the image to the container registry.

## Checks

- [x] All commits in this Pull Request are [signed](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) and Verified by Github.
- [x] All commits in this Pull Request follow the Ockam [commit message convention](https://github.com/build-trust/.github/blob/main/CONTRIBUTING.md#commit-messages).
- [x] I accept the Ockam Community [Code of Conduct](https://github.com/build-trust/.github/blob/main/CODE_OF_CONDUCT.md).
- [x] I have accepted the Ockam [Contributor License Agreement](https://github.com/build-trust/ockam-contributors/blob/main/CLA.md) by adding my Git/Github details in a row at the end of the [CONTRIBUTORS.csv](https://github.com/build-trust/ockam-contributors/blob/main/CONTRIBUTORS.csv) file in a separate pull request to the [build-trust/ockam-contributors](https://github.com/build-trust/ockam-contributors) repository. The easiest way to do this is to [edit the CONTRIBUTORS.csv](https://github.com/build-trust/ockam-contributors/edit/main/CONTRIBUTORS.csv) file in the github web UI and create a PR, this will mark the commit as verified.

2023-06-06 14:00 UTC, metaclips requested changes
Thanks for an amazing PR, changes needed for a merge. We also need to rebase this PR, the command below should suffice.
`git pull --rebase https://github.com/build-trust/ockam.git develop`

2023-06-06 14:00 UTC, metaclips commented on .github/workflows/ockam-artifact.yml
> +      - '.implementations/rust/ockam'
This should be `implementations/rust/ockam` let's remove the `.` prefix

2023-06-06 14:00 UTC, metaclips commented on .github/workflows/ockam-artifact.yml
> +      - '.implementations/rust/ockam'
We should also run workflow when there's an update to the dockerfile

2023-06-06 14:00 UTC, metaclips commented on .github/workflows/ockam-artifact.yml
> +  build_artifact:
Let's add `packages: write` and `contents: read` [permission](https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs) to this job

2023-06-06 14:00 UTC, metaclips commented on .github/workflows/ockam-artifact.yml
> +name: docker-ockam-command-artifact
Let's change this to `Ockam Command Docker Artifact Build`

2023-06-06 14:00 UTC, metaclips commented on .github/workflows/ockam-artifact.yml
> +    runs-on: ubuntu-latest
Let's pin the OS to `ubuntu-20.04`

2023-06-06 14:00 UTC, metaclips commented on .github/workflows/ockam-artifact.yml
> +            --tag ghcr.io/${ORGANIZATION}/${ARTIFACT_NAME}:latest \
`${ARTIFACT_NAME}` and `${ORGANIZATION}` are not defined.

2023-06-06 14:00 UTC, metaclips commented on .github/workflows/ockam-artifact.yml
> +            --tag ghcr.io/${ORGANIZATION}/${ARTIFACT_NAME}:latest \
Can we also tag the image as `ghcr.io/${ORGANIZATION}/${ARTIFACT_NAME}:commit_sha_that_started_build-month-day-year`. This should be `ghcr.io/${ORGANIZATION}/${ARTIFACT_NAME}:${{ github.event.pull_request.head.sha }}-$(date +'%b-%d-%Y')`

2023-06-06 14:04 UTC, rghdrizzle commented on .github/workflows/ockam-artifact.yml
> +            --tag ghcr.io/${ORGANIZATION}/${ARTIFACT_NAME}:latest \
ah yes , forgot to declare those

2023-06-07 06:21 UTC, rghdrizzle commented
> Thanks for an amazing PR, changes needed for a merge. We also need to rebase this PR, the command below should suffice.
> 
> ```shell
> git pull --rebase https://github.com/build-trust/ockam.git develop
> git push -f
> ```

changes have been made .

2023-06-08 09:32 UTC, metaclips requested changes
Little change left

2023-06-08 09:32 UTC, metaclips commented on .github/workflows/ockam-artifact.yml
> +  ARTIFACT_NAME: ockam-healthcheck
Let's change this to `ockam-artifacts`

2023-06-08 09:57 UTC, metaclips commented on .github/workflows/ockam-artifact.yml
> +  ARTIFACT_NAME: ockam-healthcheck
Let's also add a new line at the end of this workflow

2023-06-08 11:04 UTC, rghdrizzle commented on .github/workflows/ockam-artifact.yml
> +  ARTIFACT_NAME: ockam-healthcheck
Done

2023-06-08 12:48 UTC, rghdrizzle commented
I added a new line , why is still saying there is no new line in the end ?

2023-06-08 15:39 UTC, davide-baldo commented
> I added a new line , why is still saying there is no new line in the end ?

it seems like the last line contains spaces, there shouldn't be any

2023-06-09 14:06 UTC, rghdrizzle commented
@davide-baldo Should I squash the commits ?

2023-06-09 14:13 UTC, rghdrizzle commented
> @davide-baldo Should I squash the commits ? since the workflows shows an error

Well I squashed it anyways .

2023-06-09 14:21 UTC, davide-baldo commented
well done!

2023-06-09 14:26 UTC, davide-baldo commented
I just saw it, you added a submodule, why?

2023-06-09 14:32 UTC, rghdrizzle commented
> before merging, I noticed a submodule in the PR, could you tell me if is it necessary?

Im not sure if its necessary since it automatically added that when I was committing for some reason .

2023-06-09 14:33 UTC, rghdrizzle commented
> > before merging, I noticed a submodule in the PR, could you tell me if is it necessary?
> 
> Im not sure if its necessary since it automatically got added when I was committing for some reason .

2023-06-09 21:57 UTC, metaclips approved these changes
Approved, thanks @rghdrizzle

2023-06-09 21:57 UTC, metaclips commented on .github/workflows/ockam-artifact.yml
> +
There are two new lines and the last line has a tab identation.

2023-06-09 22:19 UTC, merged