refactor(rust): add more meaningful error messages for `CLiState` errors
build-trust/ockam pull request #5150
Opened 2023-06-20 09:19 UTC by adrianbenavides

Add new error types for `CliStateError` and also extend some existing errors to include more information.

For example:

```sh
# Before
$ ockam node show <nonexistent-node>
× not found

# Now
$ ockam node show <nonexistent-node>
× Unable to find node named n2
```

This change also allows us to simplify the commands where we were manually checking a `NotFound` error to write the error message. Example [here](https://github.com/build-trust/ockam/pull/5150/files#diff-0d69316ec86013b48ba4411821faebcbc204624e786f5c2811223c696e2898f9L45-L46).

2023-06-20 09:45 UTC, etorreborre approved these changes, later dismissed
Nice job 🍡

2023-06-20 12:58 UTC, adrianbenavides commented
> Nice job 🍡

I love that emoji!

2023-06-20 12:59 UTC, adrianbenavides commented
I'm leaving this unmerged until @nazmulidris gets the chance to take a look at the messages contents.

2023-06-20 16:21 UTC, nazmulidris requested changes
Great work @adrianbenavides 🎉 👏🏽 

I've added a bunch of suggestions, PLMK if they make sense, or if they need clarification 🙏🏽

2023-06-20 16:21 UTC, nazmulidris commented on implementations/rust/ockam/ockam_api/src/cli_state.rs
> +    #[error("A {resource} with name {name} already exists")]
Perhaps rephrase with: "A {resource} named {name} already exists"

2023-06-20 16:21 UTC, nazmulidris commented on implementations/rust/ockam/ockam_api/src/cli_state.rs
> +        help("try using a different name or deleting the existing {resource}")
Perhaps rephrase with: "Please try using a different name or delete the existing {resource}"

2023-06-20 16:21 UTC, nazmulidris commented on implementations/rust/ockam/ockam_api/src/cli_state.rs
> +    #[error("The path {0} is not valid")]
Perhaps rephrase with: "The path {0} is invalid"

2023-06-20 16:21 UTC, nazmulidris commented on implementations/rust/ockam/ockam_api/src/cli_state.rs
> +        help("try running 'ockam reset' to reset your local configuration")
Perhaps rephrase with: 
"Please try running 'ockam reset' to reset your local configuration"
or
"Please try running 'ockam reset --yes' to reset your local configuration"

2023-06-20 16:21 UTC, nazmulidris commented on implementations/rust/ockam/ockam_api/src/cli_state.rs
> +                return Err(CliStateError::InvalidOperation(format!(
Perhaps rephrase with: "Can't delete identity '{}' as its being used by node '{}'"

2023-06-20 16:21 UTC, nazmulidris commented on implementations/rust/ockam/ockam_command/src/identity/default.rs
> +        Err(miette!("Identity '{}' is already the default", &cmd.name))
Perhaps rephrase with: "Nothing to do as identity '{}' is already the default"

2023-06-20 16:21 UTC, nazmulidris commented on implementations/rust/ockam/ockam_command/src/message/send.rs
> +                .context("The message is not valid hex string")?
Perhaps rephrase with: "The message is not a valid hex string"

2023-06-20 16:21 UTC, nazmulidris commented on implementations/rust/ockam/ockam_command/src/node/delete.rs
> +            .plain(fmt_ok!("Node with name '{}' has been deleted.", &node_name))
Perhaps rephrase with: "The node named '{}' has been deleted."

2023-06-20 16:21 UTC, nazmulidris commented on implementations/rust/ockam/ockam_command/src/node/util.rs
> +        .wrap_err("failed to create identity")?;
Perhaps rephrase with: "Failed to create identity"

2023-06-20 16:21 UTC, nazmulidris commented on implementations/rust/ockam/ockam_command/src/tcp/inlet/create.rs
> +            return Err(miette!("Another process is listening on the provided port!").into());
Perhaps rephrase with: "Another process is already listening on the provided port!"

It would be even better to include the port number in this message, eg:
"Another process is already listening on port {PORT_NUMBER}!"

2023-06-20 16:21 UTC, nazmulidris commented on implementations/rust/ockam/ockam_command/src/trust_context/default.rs
> +        Err(miette!("Trust context '{name}' is already the default"))
Perhaps rephrase with: "Nothing to do as trust context '{name}' is already the default"

2023-06-20 16:21 UTC, nazmulidris commented on implementations/rust/ockam/ockam_command/src/trust_context/delete.rs
> +        "This will delete the trust context with name '{name}'. Do you want to continue?"
Perhaps rephrase with: "This will delete the trust context named '{name}'. Do you wish to proceed?"

2023-06-20 16:21 UTC, nazmulidris commented on implementations/rust/ockam/ockam_command/src/util/mod.rs
> +                .ok_or(miette!("Failed to parse 'node' protocol"))?
Perhaps rephrase with: "Failed to parse the 'node' protocol"

2023-06-20 16:21 UTC, nazmulidris commented on implementations/rust/ockam/ockam_command/src/vault/default.rs
> +        Err(miette!("Vault '{}' is already the default", name))
Perhaps rephrase with: "Nothing to do, as vault '{}' is already the default"

2023-06-20 16:21 UTC, nazmulidris commented on implementations/rust/ockam/ockam_command/src/vault/delete.rs
> +        "This will delete the vault with name '{name}'. Do you want to continue?"
Perhaps rephrase with: "This will delete the vault named '{name}'. Do you wish to proceed?"

2023-06-20 16:21 UTC, nazmulidris commented on implementations/rust/ockam/ockam_command/src/identity/delete.rs
> +            "Identity with name '{}' has been deleted.",
Perhaps rephrase with: "The identity named '{}' has been deleted."

2023-06-20 16:21 UTC, nazmulidris commented on implementations/rust/ockam/ockam_command/src/trust_context/delete.rs
> +        .plain(fmt_ok!("Trust context with name '{name}' has been deleted"))
Perhaps rephrase with: "The trust context named '{name}' has been deleted"

2023-06-20 16:21 UTC, nazmulidris commented on implementations/rust/ockam/ockam_command/src/vault/delete.rs
> +        .plain(fmt_ok!("Vault with name '{name}' has been deleted"))
Perhaps rephrase with: "The vault named '{name}' has been deleted"

2023-06-21 07:29 UTC, adrianbenavides commented on implementations/rust/ockam/ockam_api/src/cli_state.rs
> +    #[error("A {resource} with name {name} already exists")]
Absolutely, that's more aligned with the text we have at https://github.com/build-trust/ockam/blob/7a2e16c8dc422d7f41febfb86480926d7debd4b0/implementations/rust/ockam/ockam_command/src/error.rs#L18

2023-06-21 07:33 UTC, adrianbenavides commented on implementations/rust/ockam/ockam_api/src/cli_state.rs
> +        help("try running 'ockam reset' to reset your local configuration")
I don't know what think about saying the user to use the `force` option right away... Recommending `ockam reset` feels safer.

2023-06-21 15:38 UTC, nazmulidris commented on implementations/rust/ockam/ockam_command/src/identity/default.rs
> +        Err(miette!("Identity '{}' is already the default", &cmd.name))
To make it less verbose, you can also do "The identity '{}' is already the default"

2023-06-21 15:39 UTC, nazmulidris commented on implementations/rust/ockam/ockam_command/src/trust_context/default.rs
> +        Err(miette!("Trust context '{name}' is already the default"))
To make it less verbose, you might also consider "The trust context '{name}' is already the default"

2023-06-21 15:39 UTC, nazmulidris commented on implementations/rust/ockam/ockam_command/src/vault/default.rs
> +        Err(miette!("Vault '{}' is already the default", name))
To make it less verbose, you might also consider "The vault '{}' is already the default"

2023-06-21 19:13 UTC, nazmulidris approved these changes

2023-06-21 21:03 UTC, CAOakleyII approved these changes

2023-06-21 21:24 UTC, merged