validate credentials of receiving identity for outgoing messages in inlets and outlets
build-trust/ockam pull request #5155
Opened 2023-06-20 15:00 UTC by davide-baldo

Currently, we don't validate outgoing messages from inlets or outlets. The impact is vastly reduced by the fact that inlets/outlet communication always requires a ping/pong handshake, and this will force validation of the incoming message once during initialization. But after that, the communication will keep going regardless of the remote credential validity, this PR is aimed to fix specifically this case.

The approach used is to update the outgoing access control when the first message is received, capturing the source local_info.

2023-06-21 16:52 UTC, SanjoDeundiak requested changes

2023-06-21 16:52 UTC, SanjoDeundiak commented on implementations/rust/ockam/ockam_node/src/context/context.rs
> +    pub fn mailboxes_mut(&mut self) -> &mut Mailboxes {
I'm not sure modifying mailboxes while the worker is running (especially when the worker itself should do it) is a good idea, it's very easy to shoot yourself in the foot by, for example, creating a race condition. Is there a way to set up mailboxes from the beginning?

2023-06-21 16:52 UTC, SanjoDeundiak commented on implementations/rust/ockam/ockam_transport_tcp/src/portal/outlet_listener.rs
> +            self.options.outgoing_access_control_factory.clone(),
Can't we instantiate the outgoing access control at this point already?

2023-06-27 10:32 UTC, closed without merging

2023-06-27 10:33 UTC, davide-baldo commented
Needs heavy changes for a new design