feat(rust): update rust api examples with colored output
build-trust/ockam pull request #5662
Opened 2023-08-17 21:47 UTC by nazmulidris

Update Rust API examples so that they have nice colorized output that is easy for developers to read and understand.

## Checks

- [x] All commits in this Pull Request are [signed](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) and Verified by Github.
- [x] All commits in this Pull Request follow the Ockam [commit message convention](https://github.com/build-trust/.github/blob/main/CONTRIBUTING.md#commit-messages).
- [x] I accept the Ockam Community [Code of Conduct](https://github.com/build-trust/.github/blob/main/CODE_OF_CONDUCT.md).
- [x] I have accepted the Ockam [Contributor License Agreement](https://github.com/build-trust/ockam-contributors/blob/main/CLA.md) by adding my Git/Github details in a row at the end of the [CONTRIBUTORS.csv](https://github.com/build-trust/ockam-contributors/blob/main/CONTRIBUTORS.csv) file in a separate pull request to the [build-trust/ockam-contributors](https://github.com/build-trust/ockam-contributors) repository. The easiest way to do this is to [edit the CONTRIBUTORS.csv](https://github.com/build-trust/ockam-contributors/edit/main/CONTRIBUTORS.csv) file in the github web UI and create a PR, this will mark the commit as verified.

2023-08-23 12:24 UTC, mrinalwadhwa commented on examples/rust/get_started/examples/01-node.rs
> +    // Create a node with default implementations.
```suggestion
    // Create a node.
```

2023-08-23 12:26 UTC, mrinalwadhwa commented on examples/rust/get_started/examples/01-node.rs
> +│  │ Address:       │  │
```suggestion
│  │ Worker Address: │  │
```

2023-08-23 12:27 UTC, mrinalwadhwa requested changes, later dismissed
@nazmulidris this looks great, left a couple of minor suggestions.

2023-08-25 01:04 UTC, nazmulidris commented on examples/rust/get_started/examples/01-node.rs
> +│  │ Address:       │  │
Done!

2023-08-25 01:04 UTC, nazmulidris commented on examples/rust/get_started/examples/01-node.rs
> +    // Create a node with default implementations.
Done

2023-08-25 01:25 UTC, nazmulidris commented
@mrinalwadhwa 
- Thank you for your suggestions 🙏🏽. I've incorporated them all. 
- I've also switched to using a different dependency for ansi 256 color output (that works on linux, macos, and windows & has a compatible license).

> Also, the `lint_docs_ockam_io_rust_examples` are failing in this PR because I've not merged this PR in the `ockam-documentation` repo yet https://github.com/build-trust/ockam-documentation/pull/56

2023-08-25 01:27 UTC, nazmulidris reviewed
@mrinalwadhwa I've made all the changes you requested 👍🏽

2023-08-25 16:35 UTC, mrinalwadhwa approved these changes

2023-08-25 17:01 UTC, merged