fix(rust): handle error returned by node
build-trust/ockam pull request #6445
Opened 2023-10-10 17:44 UTC by adiSuper94

## Current behavior
Error thrown by node with `#[ockam#node]` macro is not handled

## Proposed changes
Attempt to handle it.
To do that we are having to add some constraint on what an `#[ockam#node]` function is allowed to return.
We are restricting it to return `Result<T, Error>` 

## Checks

- [ ] All commits in this Pull Request are [signed](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) and Verified by Github.
- [ ] All commits in this Pull Request follow the Ockam [commit message convention](https://github.com/build-trust/.github/blob/main/CONTRIBUTING.md#commit-messages).
- [ ] There are no Merge commits in this Pull Request. Ockam repo maintains a linear commit history. We merge Pull Requests by rebasing them onto the develop branch. Rebasing to the latest develop branch and force pushing to your Pull Request branch is okay.
- [ ] I have read and accept the Ockam Community [Code of Conduct](https://github.com/build-trust/.github/blob/main/CODE_OF_CONDUCT.md).
- [ ] I have read and accepted the Ockam [Contributor License Agreement](https://github.com/build-trust/.github/blob/main/CLA.md) by adding my Git/Github details in a row at the end of the [CONTRIBUTORS.csv](https://github.com/build-trust/ockam/blob/develop/.github/CONTRIBUTORS.csv) file in a separate pull request to the [build-trust/ockam](https://github.com/build-trust/ockam) repository. The easiest way to do this is to [edit the CONTRIBUTORS.csv](https://github.com/build-trust/ockam/edit/develop/.github/CONTRIBUTORS.csv) file in the github web UI and create a separate Pull Request, this will mark the commit as verified.

2023-10-10 17:45 UTC, adiSuper94 commented
@SanjoDeundiak how does this look for a starting point?

I also need to check if I can use send some other message that will shut the router down.

I will make changes to the examples if this approach is ok.

2023-10-11 16:19 UTC, SanjoDeundiak requested changes
I tried it, and it looks like returning an error from a main function doesn't really stop a node. I left a corresponding comment. Also, could you please run `cargo clippy` and take a look if examples compilation can be easily fixed?

2023-10-11 16:19 UTC, SanjoDeundiak commented on implementations/rust/ockam/ockam_node/src/executor.rs
> +                let _ = sender.send(NodeMessage::AbortNode).await;
It looks like `AbortNode` is not handled properly and doesn't really stop a node (should be a bug, will create an issue for that).
However, you can find the correct way to stop a node inside `Context::stop` function.

2023-10-13 01:52 UTC, adiSuper94 commented
> However, you can find the correct way to stop a node inside Context::stop function

I tried this, it works!! 

> It looks like AbortNode is not handled properly and doesn't really stop a node (should be a bug, will create an issue for that).

That would be great.

> could you please run cargo clippy and take a look if examples compilation can be easily fixed?

I tried doing that, did not show any errors. But errors do exist. clippy doesn't seem to find them. basically returning `anyhow::Result<T>` is not allowed anymore. I have fixed one such example test locally. Will do the rest too.

2023-10-17 11:51 UTC, SanjoDeundiak approved these changes, later dismissed

2023-10-17 11:52 UTC, SanjoDeundiak commented
@adiSuper94 I added small improvements and squashed the commits. We can merge as soon as CI checks succeed

2023-10-17 12:30 UTC, adiSuper94 commented
@SanjoDeundiak , thanks for pushing this.

I have a question though, I ran 'cargo clippy' from ockam root. And I did not get any failures. 
So what is the way to find these errors in local. 
Cuz running cargo test, makes my laptop sound like a helicopter 😅

2023-10-17 15:07 UTC, SanjoDeundiak commented
Created an issue for `AbortNode` handling https://github.com/build-trust/ockam/issues/6615

2023-10-17 15:07 UTC, SanjoDeundiak commented
@adiSuper94 that's weird. For me it showed the problems. Do you think you may have an outdated version?

2023-10-17 15:29 UTC, adiSuper94 commented
Do you mean outdated version of code or `clippy` ??
I am not sure. I know that I have the latest rust toolchain installed. But ockam project sets the required version to `1.71` i think.

2023-10-17 15:32 UTC, etorreborre approved these changes

2023-10-17 15:33 UTC, SanjoDeundiak commented
@adiSuper94 you can also try `clippy --no-deps --all-targets`

2023-10-17 15:34 UTC, adiSuper94 commented
I haven't pulled the changes you made to my local yet. So I'll try this and see if I get those errors  you fixed. Thanks!!

2023-10-17 18:07 UTC, merged

2023-10-17 23:35 UTC, adiSuper94 commented
@SanjoDeundiak `cargo clippy` did find the errors when I ran it with the flags you suggested.