ci: split elixir cache to save and restore cache
build-trust/ockam pull request #6536
Opened 2023-10-14 17:38 UTC by Lucif3r-in

Fixes #6508 
## Proposed changes
As described in the issue the cache need to be split into save and restore cache

## Checks

- [ ] All commits in this Pull Request are [signed](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) and Verified by Github.
- [ ] All commits in this Pull Request follow the Ockam [commit message convention](https://github.com/build-trust/.github/blob/main/CONTRIBUTING.md#commit-messages).
- [ ] There are no Merge commits in this Pull Request. Ockam repo maintains a linear commit history. We merge Pull Requests by rebasing them onto the develop branch. Rebasing to the latest develop branch and force pushing to your Pull Request branch is okay.
- [ ] I have read and accept the Ockam Community [Code of Conduct](https://github.com/build-trust/.github/blob/main/CODE_OF_CONDUCT.md).
- [ ] I have read and accepted the Ockam [Contributor License Agreement](https://github.com/build-trust/.github/blob/main/CLA.md) by adding my Git/Github details in a row at the end of the [CONTRIBUTORS.csv](https://github.com/build-trust/ockam/blob/develop/.github/CONTRIBUTORS.csv) file in a separate pull request to the [build-trust/ockam](https://github.com/build-trust/ockam) repository. The easiest way to do this is to [edit the CONTRIBUTORS.csv](https://github.com/build-trust/ockam/edit/develop/.github/CONTRIBUTORS.csv) file in the github web UI and create a separate Pull Request, this will mark the commit as verified.

2023-10-14 17:52 UTC, mrinalwadhwa commented
@Lucif3r-in Thank you for spending time on this, before we can merge please

- [ ] Accept the Ockam [Contributor License Agreement](https://github.com/build-trust/ockam-contributors/blob/main/CLA.md) by adding your Git/Github details in a row at the end of the [CONTRIBUTORS.csv](https://github.com/build-trust/ockam/blob/develop/.github/CONTRIBUTORS.csv) file in a separate new pull request to the [build-trust/ockam](https://github.com/build-trust/ockam) repository.

The easiest way to do this is to [edit the CONTRIBUTORS.csv](https://github.com/build-trust/ockam/edit/develop/.github/CONTRIBUTORS.csv) file in the github web UI and create a PR, this will mark the commit as verified.

2023-10-14 18:39 UTC, Lucif3r-in commented
Done @mrinalwadhwa 🚀

2023-10-16 11:17 UTC, metaclips requested changes
Thanks @Lucif3r-in for taking steps on this PR, few changes left and we should get it merged

2023-10-16 11:17 UTC, metaclips commented on .github/actions/elixir_cache/action.yml
> +      - name: Save Cache
Let's rename this to `Restore and save cache

2023-10-16 11:17 UTC, metaclips commented on .github/actions/elixir_cache/action.yml
> +        if: steps.schedule.outputs.schedule == 'true'
we can change this line to `if: ${{ github.event_name == 'schedule' }}`

2023-10-16 11:17 UTC, metaclips commented on .github/actions/elixir_cache/action.yml
> +        id: schedule
I don't think there's a need for this step, we can call all other steps conditionally as `${{ github.event_name == 'schedule' }}`, please check below review.

2023-10-16 11:17 UTC, metaclips commented on .github/actions/elixir_cache/action.yml
> +          key: cache-elixir-${{ github.workflow }}-${{ github.job }}-${{ inputs.job_name }}-${{ hashFiles('**/mix.lock') }}
Let's also add a restore cache key
```
restore-keys: |
            cache-elixir-${{ github.workflow }}-${{ github.job }}-${{ inputs.job_name }}-
```

2023-10-16 11:17 UTC, metaclips commented on .github/actions/elixir_cache/action.yml
> +            cache-elixir-${{ github.workflow }}-${{ github.job }}-${{ inputs.job_name }}-
For this step, we only want to restore cache `if ${{ github.event_name != 'schedule' }}`, for this, we will only be [using the restore cache action](https://github.com/actions/cache/tree/main/restore#only-restore-cache)

```yaml
  - uses: actions/cache/restore@67b839edb68371cc5014f6cea11c9aa77238de78
    with:
          path: |
            **/deps
            **/_build
          key: cache-elixir-${{ github.workflow }}-${{ github.job }}-${{ inputs.job_name }}-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            cache-elixir-${{ github.workflow }}-${{ github.job }}-${{ inputs.job_name }}-
```

2023-10-16 11:17 UTC, metaclips commented on .github/actions/elixir_cache/action.yml
> +    - cron: '0 0 * * *'
This is a [composite action](https://docs.github.com/en/actions/creating-actions/creating-a-composite-action), it's an action that's re-usable across multiple workflows, we can set a cron job here as the [`on: event` only triggers at the workflow level](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#on), let's remove this

2023-10-17 16:38 UTC, Lucif3r-in commented
Hey @metaclips sorry for the delay. I have made the requested changes please review😊

2023-10-17 18:23 UTC, metaclips approved these changes

2023-10-17 18:54 UTC, polvorin approved these changes

2023-10-17 19:44 UTC, merged