fix(rust): use the transaction api properly with sqlx
build-trust/ockam pull request #7005
Opened 2023-11-30 20:00 UTC by etorreborre

This PR fixes the use of transactions with `sqlx`

2023-11-30 22:37 UTC, SanjoDeundiak requested changes

2023-11-30 22:37 UTC, SanjoDeundiak commented on implementations/rust/ockam/ockam_identity/src/identities/storage/identity_attributes_repository_sql.rs
> -        let transaction = self.database.begin().await.into_core()?;
Why do you think transaction is not required here?

2023-11-30 22:37 UTC, SanjoDeundiak commented on implementations/rust/ockam/ockam_api/src/cli_state/storage/identities_repository_sql.rs
> -        let transaction = self.database.begin().await.into_core()?;
Why do you think transaction is not required here?

2023-11-30 22:37 UTC, SanjoDeundiak commented on implementations/rust/ockam/ockam_api/src/cli_state/storage/projects_repository_sql.rs
> -        let transaction = self.database.begin().await.into_core()?;
Why do you think transaction is not required here?

2023-12-01 09:39 UTC, etorreborre commented on implementations/rust/ockam/ockam_api/src/cli_state/storage/identities_repository_sql.rs
> -        let transaction = self.database.begin().await.into_core()?;
In the 3 examples you pointed out, the code is reusing an existing query which is not executed with a transaction. Some better code could be to include the query (not its execution) inside the transaction. But maybe some better behaviour would be to forbid an update for a `NamedIdentity` altogether. 
I think it's worth spending some time improving the storage semantics of those named/default entities but I propose that we do it in another PR.

2023-12-01 13:58 UTC, SanjoDeundiak approved these changes

2023-12-01 14:42 UTC, merged