fix(no_std_executor): Ensure thread-safe initialization of Executor i…
build-trust/ockam pull request #7242
Opened 2023-12-25 19:48 UTC by younes-io

…n current function

- Introduced atomic operations to prevent concurrent initialization of Executor
- Utilized compare_exchange_weak for safe and single initialization
- Enhanced overall thread safety and memory safety in a no_std environment

## Current behavior

## Proposed changes

## Checks

- [ ] All commits in this Pull Request are [signed](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) and Verified by Github.
- [ ] All commits in this Pull Request follow the Ockam [commit message convention](https://github.com/build-trust/.github/blob/main/CONTRIBUTING.md#commit-messages).
- [ ] There are no Merge commits in this Pull Request. Ockam repo maintains a linear commit history. We merge Pull Requests by rebasing them onto the develop branch. Rebasing to the latest develop branch and force pushing to your Pull Request branch is okay.
- [ ] I have read and accept the Ockam Community [Code of Conduct](https://github.com/build-trust/.github/blob/main/CODE_OF_CONDUCT.md).
- [ ] I have read and accepted the Ockam [Contributor License Agreement](https://github.com/build-trust/.github/blob/main/CLA.md) by adding my Git/Github details in a row at the end of the [CONTRIBUTORS.csv](https://github.com/build-trust/ockam/blob/develop/.github/CONTRIBUTORS.csv) file in a separate pull request to the [build-trust/ockam](https://github.com/build-trust/ockam) repository. The easiest way to do this is to [edit the CONTRIBUTORS.csv](https://github.com/build-trust/ockam/edit/develop/.github/CONTRIBUTORS.csv) file in the github web UI and create a separate Pull Request, this will mark the commit as verified.

2023-12-26 16:02 UTC, younes-io commented on implementations/rust/ockam/ockam_executor/src/executor.rs
> -    static INIT: AtomicBool = AtomicBool::new(false);
BTW, whoever is going to review this; I got this code out to make it a singleton. Is that OK ?

2024-01-13 08:57 UTC, younes-io commented
Can someone help me fix the commit msg ?

2024-01-21 11:58 UTC, SanjoDeundiak requested changes
Could you please take a look at why CI fails?

2024-03-09 18:38 UTC, younes-io commented
Closing because this keeps failing and I get a million emails a day... even with the commits.. it's not solved..

2024-03-09 18:38 UTC, closed without merging