doc: add an example of a portal using the Amazon Bedrock service
build-trust/ockam pull request #7874
Opened 2024-04-09 17:10 UTC by etorreborre

The model used as an example is the Amazon "Titan Text G1 - Lite" model.

2024-04-15 16:43 UTC, adrianbenavides approved these changes, later dismissed

2024-04-15 16:45 UTC, snandam requested changes, later dismissed

2024-04-15 16:45 UTC, snandam commented on examples/command/portals/ai/amazon_bedrock/health_corp/run.sh
> +        --description "Allow TCP egress and Postgres ingress")
Replace `Postgres` with `Bedrock`

2024-04-15 16:45 UTC, snandam commented on examples/command/portals/ai/amazon_bedrock/run.sh
> +    # Create an enrollment ticket to enroll the identity used by an ockam node that will run adjacent to the postgres
Replace `postgre` with `Bedrock`

2024-04-17 07:37 UTC, mrinalwadhwa approved these changes

2024-04-17 07:50 UTC, merged