feat(rust): add `tcp-test` tool to measure portal properties
build-trust/ockam pull request #8704
Opened 2024-12-16 12:45 UTC by davide-baldo

This tool is useful to test the portal capabilities and operates as a **generic** TCP client and server.
It also implements (unsafe) TLS, which is useful for performance comparison.

2024-12-16 21:43 UTC, SanjoDeundiak requested changes
That looks very useful !

2024-12-16 21:43 UTC, SanjoDeundiak commented on tools/tcp-test/src/main.rs
> +                println!(
Did you compare to iperf3? In terms of results and in terms of how it's implemented? My concern is the fact that stream write success, doesn't guarantee that the data was received (or will be received at all) on the other end. It doesn't wait for the ack, therefore I'm not sure  how correct is the throughput computation here. I would call it "sending throughput" compared to "receiving throughput". The second one is the real one. I understand that due to how TCP works sending throughput should get closer and closer to receiving throughput eventually, but have no idea how different the values can theoretically be in the meantime

2024-12-16 21:43 UTC, SanjoDeundiak commented on tools/tcp-test/deploy
> +TARGET_ARCHITECTURE=$(ssh uname -m)
Does that assume that the machine we deploy to uses the same architecture as the machine we're running the script on? Is that intended?

2024-12-16 21:43 UTC, SanjoDeundiak commented on tools/tcp-test/README.md
> +$ tcp-test echo 1234
Should the command be different from the previous somehow?

2024-12-16 21:43 UTC, SanjoDeundiak commented on tools/tcp-test/README.md
> +Throughput: 47.56066Gbits/s
Let's leave maybe 2 digits after the comma :)

2024-12-16 21:43 UTC, SanjoDeundiak commented on tools/tcp-test/deploy
> +    /usr/bin/env ssh -q -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=QUIET -o ConnectTimeout=5 "${SSH_ENDPOINT}" "$@"
I'm a little bit concerned that some arguments for ssh and scp are different, e.g. `-p` is port for ssh, but `-P` for scp. Not sure that's a real issue, just FYI

2024-12-16 21:43 UTC, SanjoDeundiak commented on tools/tcp-test/src/server.rs
> +#[derive(Clone)]
nit: might derive Copy

2024-12-16 21:43 UTC, SanjoDeundiak commented on tools/tcp-test/src/main.rs
> +    let outgoing_buffer = [0u8; 64 * 1024];
Let's move this value (and for other buffers) to a constant or a variable. Not sure if it should be adjustable

2024-12-16 21:43 UTC, SanjoDeundiak commented on tools/tcp-test/src/server.rs
> +                                .push_back((bytes, incoming_buffer));
nit: should be possible to set length on the buffer after read, and clear it before putting it back after write

2024-12-17 11:15 UTC, davide-baldo commented on tools/tcp-test/README.md
> +$ tcp-test echo 1234
yes! it was a typo!

2024-12-17 11:18 UTC, davide-baldo commented on tools/tcp-test/deploy
> +TARGET_ARCHITECTURE=$(ssh uname -m)
Nope, we assume it's different, and cross is always used to build (even when the arch is the same, to avoid glibc-related issues)

2024-12-17 11:45 UTC, davide-baldo commented on tools/tcp-test/src/main.rs
> +                println!(
It's also naive, but both server and client gives you a throughput report.
Also, we won't be able to compare with iperf without zerocopy.
It's mostly meant to compare performance with and without TLS, as long as both are using the same implementation it should be good enough.

2024-12-17 11:51 UTC, davide-baldo commented on tools/tcp-test/src/server.rs
> +                                .push_back((bytes, incoming_buffer));
We could use it, but we would need to call `resize(.capacity(), 0)` before calling `read()`, and it would fill with zeroes every time

2024-12-17 11:53 UTC, davide-baldo commented on tools/tcp-test/deploy
> +    /usr/bin/env ssh -q -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=QUIET -o ConnectTimeout=5 "${SSH_ENDPOINT}" "$@"
I double checked, these parameters overlap 👍

2024-12-17 13:00 UTC, SanjoDeundiak commented on tools/tcp-test/src/main.rs
> +                println!(
Actually, now I suspect iperf3 does the same

2024-12-17 13:08 UTC, SanjoDeundiak commented on tools/tcp-test/deploy
> +TARGET_ARCHITECTURE=$(ssh uname -m)
I missed the `ssh` part :)

2024-12-17 15:35 UTC, SanjoDeundiak approved these changes

2024-12-17 15:53 UTC, merged